# Generated by GitHub Copilot
from __future__ import annotations

import re
from dataclasses import dataclass
from html import escape
import json
from pathlib import Path
import shutil
import subprocess
from typing import Any, cast
from urllib.parse import urlparse

from bs4 import BeautifulSoup, Tag

from app.models import DeckVisualKind, Entry, GeneratedExecutiveDeck, GeneratedExecutiveDeckSlide, TimelineStoryScope
from app.schemas import TimelineStoryArtifactSavePayload
from app.services.entries import utc_now_iso


_REPO_ROOT = Path(__file__).resolve().parents[2]
_RENDERER_SCRIPT = _REPO_ROOT / "scripts" / "render_story_deck.mjs"
_EXECUTIVE_THEME_NAME = "eventtracker-executive"
_ALLOWED_DECK_HTML_TAGS = {
    "a",
    "blockquote",
    "br",
    "div",
    "em",
    "footer",
    "h1",
    "h2",
    "h3",
    "header",
    "li",
    "ol",
    "p",
    "section",
    "small",
    "span",
    "strong",
    "ul",
}
_ALLOWED_DECK_HTML_ATTRIBUTES = {
    "a": {"href", "title", "class"},
    "blockquote": {"class"},
    "div": {"class", "id", "data-slide-key", "style"},
    "footer": {"class"},
    "h1": {"class"},
    "h2": {"class"},
    "h3": {"class"},
    "header": {"class"},
    "li": {"class"},
    "ol": {"class"},
    "p": {"class"},
    "section": {
        "class",
        "id",
        "data-slide-key",
        "data-marpit-pagination",
        "data-marpit-pagination-total",
    },
    "small": {"class"},
    "span": {"class"},
    "strong": {"class"},
    "ul": {"class"},
}


class StoryDeckError(RuntimeError):
    pass


class StoryDeckRuntimeUnavailableError(StoryDeckError):
    pass


class StoryDeckRenderError(StoryDeckError):
    pass


@dataclass(slots=True)
class ExecutiveDeckMarkdownDocument:
    markdown: str
    citation_orders_by_slide: dict[str, list[int]]
    visual_kinds: list[str]


@dataclass(slots=True)
class RenderedDeckDocument:
    html: str
    css: str
    compiler_name: str
    compiler_version: str | None


@dataclass(slots=True)
class SlideRenderQueue:
    body_points: list[str]
    callouts: list[str]
    consumed_body_points: int = 0
    consumed_callouts: int = 0

    def take_body_points(self, limit: int) -> list[str]:
        """Consume up to *limit* remaining body points without repeating them."""
        start = self.consumed_body_points
        end = min(len(self.body_points), start + limit)
        self.consumed_body_points = end
        return self.body_points[start:end]

    def take_callouts(self, limit: int) -> list[str]:
        """Consume up to *limit* remaining callouts without repeating them."""
        start = self.consumed_callouts
        end = min(len(self.callouts), start + limit)
        self.consumed_callouts = end
        return self.callouts[start:end]

    def remaining_body_points(self) -> list[str]:
        """Return body points that have not already been rendered elsewhere."""
        return self.body_points[self.consumed_body_points :]

    def remaining_callouts(self) -> list[str]:
        """Return callouts that have not already been rendered elsewhere."""
        return self.callouts[self.consumed_callouts :]


def build_executive_deck_artifact(
    deck: GeneratedExecutiveDeck,
    scope: TimelineStoryScope,
    entries: list[Entry],
    *,
    generated_utc: str,
) -> TimelineStoryArtifactSavePayload:
    """Compile a structured executive deck into a persistence-ready story artifact."""
    markdown_document = build_executive_deck_markdown(deck, entries)
    rendered_document = render_story_deck_markdown(markdown_document.markdown)
    metadata = {
        "deck_version": "v1",
        "theme_name": _EXECUTIVE_THEME_NAME,
        "slide_count": len(deck.slides),
        "source_entry_count": deck.source_entry_count,
        "provider_name": deck.provider_name,
        "truncated_input": deck.truncated_input,
        "scope_snapshot": {
            "scope_type": scope.scope_type,
            "group_id": scope.group_id,
            "query_text": scope.query_text,
            "year": scope.year,
            "month": scope.month,
        },
        "citation_orders_by_slide": markdown_document.citation_orders_by_slide,
        "visual_kinds": markdown_document.visual_kinds,
        "generation_warning": None,
    }
    return TimelineStoryArtifactSavePayload(
        artifact_kind="executive_deck",
        source_format="marpit_markdown",
        source_text=markdown_document.markdown,
        compiled_html=sanitize_compiled_deck_html(rendered_document.html),
        compiled_css=sanitize_compiled_deck_css(rendered_document.css),
        metadata_json=json.dumps(metadata, separators=(",", ":"), sort_keys=True),
        generated_utc=generated_utc,
        compiled_utc=utc_now_iso(),
        compiler_name=rendered_document.compiler_name,
        compiler_version=rendered_document.compiler_version,
    )


def build_executive_deck_markdown(
    deck: GeneratedExecutiveDeck,
    entries: list[Entry],
) -> ExecutiveDeckMarkdownDocument:
    """Assemble deterministic Marpit markdown from validated deck data."""
    entry_lookup = {entry.id: entry for entry in entries}
    citation_orders_by_entry_id: dict[int, int] = {}
    citation_orders_by_slide: dict[str, list[int]] = {}
    visual_kinds: list[str] = []
    lines = [
        "---",
        "marpit: true",
        f"theme: {_EXECUTIVE_THEME_NAME}",
        "paginate: true",
        "---",
    ]

    for index, slide in enumerate(deck.slides):
        if index > 0:
            lines.extend(["", "---"])

        slide_citation_orders = _resolve_slide_citation_orders(
            slide,
            entry_lookup=entry_lookup,
            citation_orders_by_entry_id=citation_orders_by_entry_id,
        )
        citation_orders_by_slide[slide.slide_key] = slide_citation_orders
        for visual_kind in slide.visuals:
            if visual_kind not in visual_kinds:
                visual_kinds.append(visual_kind)

        lines.extend(
            _build_slide_markup(
                deck,
                slide,
                index=index,
                entry_lookup=entry_lookup,
                citation_orders_by_entry_id=citation_orders_by_entry_id,
                citation_orders=slide_citation_orders,
            )
        )

    return ExecutiveDeckMarkdownDocument(
        markdown="\n".join(lines).strip() + "\n",
        citation_orders_by_slide=citation_orders_by_slide,
        visual_kinds=visual_kinds,
    )


def render_story_deck_markdown(markdown: str) -> RenderedDeckDocument:
    """Render Marpit markdown into standalone HTML and CSS through the Node wrapper."""
    node_path = shutil.which("node")
    if node_path is None:
        raise StoryDeckRuntimeUnavailableError(
            "Executive presentation generation is unavailable because Node.js is not installed."
        )

    try:
        result = subprocess.run(
            [node_path, str(_RENDERER_SCRIPT)],
            input=markdown,
            capture_output=True,
            text=True,
            encoding="utf-8",
            cwd=_REPO_ROOT,
            timeout=30,
            check=False,
        )
    except FileNotFoundError as exc:
        raise StoryDeckRuntimeUnavailableError(
            "Executive presentation generation is unavailable because the deck renderer could not be started."
        ) from exc
    except subprocess.TimeoutExpired as exc:
        raise StoryDeckRenderError(
            "Executive presentation generation timed out during deck compilation."
        ) from exc

    payload = _parse_renderer_payload(result.stdout, result.stderr)
    if result.returncode != 0 or not payload.get("ok"):
        error_message = str(payload.get("error") or "Executive presentation generation failed.")
        if _looks_like_missing_runtime(error_message):
            raise StoryDeckRuntimeUnavailableError(error_message)
        raise StoryDeckRenderError(error_message)

    return RenderedDeckDocument(
        html=str(payload.get("html", "")),
        css=str(payload.get("css", "")),
        compiler_name=str(payload.get("compilerName") or "marpit"),
        compiler_version=(
            str(payload.get("compilerVersion"))
            if payload.get("compilerVersion") is not None
            else None
        ),
    )


def sanitize_compiled_deck_html(value: str) -> str:
    """Strip unsafe tags and attributes from compiled presentation HTML."""
    if not value:
        return ""

    soup = BeautifulSoup(value, "html.parser")
    for tag in soup.find_all(True):
        if not isinstance(tag, Tag):
            continue
        if tag.name in {"script", "style"}:
            tag.decompose()
            continue
        if tag.name not in _ALLOWED_DECK_HTML_TAGS:
            tag.unwrap()
            continue

        allowed_attributes = _ALLOWED_DECK_HTML_ATTRIBUTES.get(tag.name, set())
        sanitized_attributes: dict[str, str | list[str]] = {}
        for attribute_name, attribute_value in tag.attrs.items():
            if attribute_name not in allowed_attributes:
                continue
            if tag.name == "a" and attribute_name == "href":
                href = str(attribute_value).strip()
                if _is_safe_story_href(href):
                    sanitized_attributes[attribute_name] = href
                continue
            if attribute_name == "style":
                style_value = str(attribute_value).strip()
                if _is_safe_deck_style(style_value):
                    sanitized_attributes[attribute_name] = style_value
                continue
            sanitized_attributes[attribute_name] = cast(str | list[str], attribute_value)
        tag.attrs = cast(Any, sanitized_attributes)

    return str(soup)


def sanitize_compiled_deck_css(value: str) -> str:
    """Reject unsafe CSS constructs before persisting compiled deck styles."""
    if not value:
        return ""

    normalized = value.replace("\r\n", "\n").strip()
    lowered = normalized.lower()
    for forbidden_fragment in ("@import", "expression(", "javascript:", "-moz-binding"):
        if forbidden_fragment in lowered:
            raise StoryDeckRenderError(
                "Executive presentation generation produced unsupported CSS content."
            )
    return normalized


def _resolve_slide_citation_orders(
    slide: GeneratedExecutiveDeckSlide,
    *,
    entry_lookup: dict[int, Entry],
    citation_orders_by_entry_id: dict[int, int],
) -> list[int]:
    """Assign stable citation order numbers across the full deck."""
    citation_orders: list[int] = []
    for entry_id in slide.citations:
        if entry_id not in entry_lookup:
            continue
        if entry_id not in citation_orders_by_entry_id:
            citation_orders_by_entry_id[entry_id] = len(citation_orders_by_entry_id) + 1
        citation_orders.append(citation_orders_by_entry_id[entry_id])
    return citation_orders


def _build_slide_markup(
    deck: GeneratedExecutiveDeck,
    slide: GeneratedExecutiveDeckSlide,
    *,
    index: int,
    entry_lookup: dict[int, Entry],
    citation_orders_by_entry_id: dict[int, int],
    citation_orders: list[int],
) -> list[str]:
    """Create the HTML-backed Marpit slide markup for one structured slide."""
    effective_visuals = _effective_visuals_for_slide(slide)
    lines = [
        f'<div class="et-slide et-slide--{slide.purpose}" data-slide-key="{escape(slide.slide_key)}">',
        f'<header class="et-slide-header"><p class="et-slide-kicker">{escape(_format_slide_purpose(slide.purpose))}</p>',
    ]
    if slide.purpose == "title":
        lines.append(f"<h1>{escape(deck.title)}</h1>")
        subtitle = deck.subtitle or slide.headline
        if subtitle and subtitle != deck.title:
            lines.append(f'<p class="et-slide-subtitle">{escape(subtitle)}</p>')
    elif slide.purpose == "thank_you":
        lines.append('<h1>Thank You!</h1>')
        subtitle = slide.headline if slide.headline.lower() not in ("thank you", "thank you!") else ""
        if subtitle:
            lines.append(f'<p class="et-slide-subtitle">{escape(subtitle)}</p>')
    else:
        lines.append(f"<h1>{escape(slide.headline)}</h1>")
    lines.append("</header>")

    render_queue = _build_slide_render_queue(slide)
    visual_lines = _build_visual_markup(effective_visuals, render_queue)

    if _should_render_residual_slide_copy(slide, visual_lines):
        remaining_body_points = render_queue.remaining_body_points()
        if remaining_body_points:
            lines.append('<div class="et-point-list"><ul>')
            for body_point in remaining_body_points:
                lines.append(f"<li>{escape(body_point)}</li>")
            lines.append("</ul></div>")

        remaining_callouts = render_queue.remaining_callouts()
        if remaining_callouts:
            lines.append('<div class="et-callout-list">')
            for callout in remaining_callouts:
                lines.append(f'<p class="et-callout">{escape(callout)}</p>')
            lines.append("</div>")

    lines.extend(visual_lines)
    lines.append(
        _build_slide_sources(
            slide,
            entry_lookup=entry_lookup,
            citation_orders_by_entry_id=citation_orders_by_entry_id,
            citation_orders=citation_orders,
        )
    )
    lines.append("</div>")
    return lines


def _build_visual_markup(
    visual_kinds: list[DeckVisualKind],
    render_queue: SlideRenderQueue,
) -> list[str]:
    """Translate requested visual kinds into script-free HTML blocks."""
    lines: list[str] = []
    for visual_kind in visual_kinds:
        if visual_kind == "kpi_strip":
            lines.extend(_build_kpi_strip_markup(render_queue))
        elif visual_kind == "phase_timeline":
            lines.extend(_build_phase_timeline_markup(render_queue))
        elif visual_kind == "pull_quote":
            lines.extend(_build_pull_quote_markup(render_queue))
        elif visual_kind == "bar_chart":
            lines.extend(_build_bar_chart_markup(render_queue))
        elif visual_kind == "stat_card":
            lines.extend(_build_stat_card_markup(render_queue))
        elif visual_kind == "icon_grid":
            lines.extend(_build_icon_grid_markup(render_queue))
    return lines


def _effective_visuals_for_slide(slide: GeneratedExecutiveDeckSlide) -> list[DeckVisualKind]:
    """Constrain visual combinations on slides that should stay especially concise."""
    if slide.purpose != "title" or len(slide.visuals) <= 1:
        return slide.visuals

    preferred_order = [
        "stat_card",
        "kpi_strip",
        "icon_grid",
        "pull_quote",
        "bar_chart",
        "phase_timeline",
    ]
    for preferred_kind in preferred_order:
        if preferred_kind in slide.visuals:
            return [preferred_kind]
    return slide.visuals[:1]


def _should_render_residual_slide_copy(
    slide: GeneratedExecutiveDeckSlide,
    visual_lines: list[str],
) -> bool:
    """Keep title slides visually sparse once a primary visual has already been rendered."""
    if slide.purpose == "title" and visual_lines:
        return False
    return True


def _build_kpi_strip_markup(render_queue: SlideRenderQueue) -> list[str]:
    """Render concise signal cards from slide callouts or body points."""
    signals = render_queue.take_callouts(3)
    if not signals:
        signals = render_queue.take_body_points(3)
    if not signals:
        return []

    lines = ['<div class="et-kpi-strip">']
    for index, signal in enumerate(signals, start=1):
        lines.extend(
            [
                '<div class="et-kpi-card">',
                f'<span class="et-kpi-label">Signal {index}</span>',
                f"<strong>{escape(signal)}</strong>",
                "</div>",
            ]
        )
    lines.append("</div>")
    return lines


def _build_phase_timeline_markup(render_queue: SlideRenderQueue) -> list[str]:
    """Render a simple phase timeline from the slide's ordered body points."""
    phases = render_queue.take_body_points(6)
    if not phases:
        return []

    lines = ['<ol class="et-phase-timeline">']
    for phase in phases:
        lines.append(f"<li>{escape(phase)}</li>")
    lines.append("</ol>")
    return lines


def _build_pull_quote_markup(render_queue: SlideRenderQueue) -> list[str]:
    """Render a pull quote from the slide's strongest callout text."""
    quote_candidates = render_queue.take_callouts(1)
    if not quote_candidates:
        quote_candidates = render_queue.take_body_points(1)
    quote_text = quote_candidates[0] if quote_candidates else ""
    if not quote_text:
        return []
    return [
        '<blockquote class="et-pull-quote">',
        f"<p>{escape(quote_text)}</p>",
        "</blockquote>",
    ]


def _build_bar_chart_markup(render_queue: SlideRenderQueue) -> list[str]:
    """Render a CSS-only horizontal bar chart from callouts (labels) and body_points (descriptions)."""
    items = render_queue.take_callouts(5)
    if not items:
        items = render_queue.take_body_points(5)
    if not items:
        return []

    lines = ['<div class="et-bar-chart">']
    bar_widths = [95, 72, 58, 45, 38]
    for index, item in enumerate(items):
        width = bar_widths[index] if index < len(bar_widths) else 35
        lines.extend([
            '<div class="et-bar-row">',
            f'<span class="et-bar-label">{escape(item)}</span>',
            f'<div class="et-bar-track"><div class="et-bar-fill" style="width:{width}%"></div></div>',
            '</div>',
        ])
    lines.append("</div>")
    return lines


def _build_stat_card_markup(render_queue: SlideRenderQueue) -> list[str]:
    """Render large stat cards from callouts (big numbers/metrics)."""
    stats = render_queue.take_callouts(4)
    if not stats:
        stats = render_queue.take_body_points(4)
    if not stats:
        return []

    lines = ['<div class="et-stat-grid">']
    for stat in stats:
        lines.extend([
            '<div class="et-stat-card">',
            f'<span class="et-stat-value">{escape(stat)}</span>',
            '</div>',
        ])
    lines.append("</div>")
    return lines


def _build_icon_grid_markup(render_queue: SlideRenderQueue) -> list[str]:
    """Render a grid of labeled items from body_points."""
    items = render_queue.take_body_points(6)
    if not items:
        items = render_queue.take_callouts(6)
    if not items:
        return []

    _ICONS = ["\u25cf", "\u25b6", "\u2605", "\u2666", "\u25a0", "\u2756"]
    lines = ['<div class="et-icon-grid">']
    for index, item in enumerate(items):
        icon = _ICONS[index % len(_ICONS)]
        lines.extend([
            '<div class="et-icon-item">',
            f'<span class="et-icon-symbol">{icon}</span>',
            f'<span class="et-icon-label">{escape(item)}</span>',
            '</div>',
        ])
    lines.append("</div>")
    return lines


def _build_slide_render_queue(slide: GeneratedExecutiveDeckSlide) -> SlideRenderQueue:
    """Prepare per-slide text content so each item renders at most once."""
    body_points = _dedupe_text_items(slide.body_points)
    body_point_keys = {_normalize_content_key(item) for item in body_points}
    callouts: list[str] = []
    seen_callout_keys: set[str] = set()
    for callout in _dedupe_text_items(slide.callouts):
        normalized_key = _normalize_content_key(callout)
        if not normalized_key or normalized_key in body_point_keys:
            continue
        if normalized_key in seen_callout_keys:
            continue
        seen_callout_keys.add(normalized_key)
        callouts.append(callout)
    return SlideRenderQueue(body_points=body_points, callouts=callouts)


def _dedupe_text_items(items: list[str]) -> list[str]:
    """Collapse repeated model output while preserving first-seen order."""
    deduped_items: list[str] = []
    seen_keys: set[str] = set()
    for item in items:
        normalized_key = _normalize_content_key(item)
        if not normalized_key or normalized_key in seen_keys:
            continue
        seen_keys.add(normalized_key)
        deduped_items.append(item)
    return deduped_items


def _normalize_content_key(value: str) -> str:
    """Normalize slide copy so exact duplicates can be removed safely."""
    collapsed = " ".join(value.split()).strip().lower()
    return re.sub(r"[^0-9a-z]+", " ", collapsed).strip()


def _build_slide_sources(
    slide: GeneratedExecutiveDeckSlide,
    *,
    entry_lookup: dict[int, Entry],
    citation_orders_by_entry_id: dict[int, int],
    citation_orders: list[int],
) -> str:
    """Build the compact footer used to ground each slide in scoped entries."""
    source_links: list[str] = []
    for entry_id in slide.citations:
        entry = entry_lookup[entry_id]
        citation_order = citation_orders_by_entry_id[entry_id]
        link_title = entry.display_date or entry.title
        source_links.append(
            '<a class="et-source-link" '
            f'href="/entries/{entry.id}/view" '
            f'title="{escape(link_title)}">'
            f'[{citation_order}] {escape(entry.title)}</a>'
        )
    if not source_links:
        return '<footer class="et-slide-sources">No sources linked.</footer>'
    joined_links = " ".join(source_links)
    return f'<footer class="et-slide-sources">Sources {joined_links}</footer>'


def _build_pull_quote_markup_label() -> str:
    """Provide a stable label hook for the theme without embedding raw copy."""
    return "Key quote"


def _format_slide_purpose(value: str) -> str:
    """Convert internal slide-purpose identifiers into short labels."""
    labels = {
        "title": "Executive presentation",
        "toc": "Agenda",
        "summary": "Summary",
        "section_header": "",
        "turning_point": "Turning point",
        "highlight": "Highlight",
        "trajectory": "Trajectory",
        "quote": _build_pull_quote_markup_label(),
        "close": "Key takeaways",
        "thank_you": "",
    }
    return labels.get(value, "Executive slide")


def _parse_renderer_payload(stdout: str, stderr: str) -> dict[str, object]:
    """Decode the renderer's JSON response and preserve helpful fallback errors."""
    raw_payload = stdout.strip() or stderr.strip()
    if not raw_payload:
        return {"ok": False, "error": "Executive presentation generation failed."}
    try:
        parsed = json.loads(raw_payload)
    except json.JSONDecodeError:
        return {"ok": False, "error": raw_payload}
    if not isinstance(parsed, dict):
        return {"ok": False, "error": "Executive presentation generation failed."}
    return parsed


def _looks_like_missing_runtime(error_message: str) -> bool:
    """Detect missing Node or Marpit dependencies from renderer failures."""
    lowered = error_message.lower()
    return "node.js" in lowered or "cannot find package '@marp-team/marpit'" in lowered or "marpit package is not installed" in lowered


def _is_safe_story_href(value: str) -> bool:
    """Allow only in-app relative links or fragment links in stored deck HTML."""
    if value.startswith("#"):
        return True
    if value.startswith("/"):
        parsed = urlparse(value)
        return parsed.scheme == "" and parsed.netloc == ""
    return False


def _is_safe_deck_style(value: str) -> bool:
    """Allow only width-percentage styles used by bar chart fills."""
    return bool(re.fullmatch(r"width:\s*\d{1,3}%", value))