// Generated by GitHub Copilot
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tstests/e2e',
  testMatch: '**/*.spec.ts',
  fullyParallel: true,
  // Each test boots its own isolated server inside the test-scoped e2eSession
  // fixture (allowed up to 120s by the harness), so the per-test budget must
  // cover that boot plus the test body even when workers run in parallel.
  timeout: 180_000,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  outputDir: 'test-results/playwright-artifacts',
  reporter: process.env.CI
    ? [['list'], ['html', { open: 'never' }], ['junit', { outputFile: 'test-results/playwright/results.xml' }]]
    : [['list'], ['html', { open: 'never' }]],
  // Match the harness default action timeout (page.setDefaultTimeout(10_000)). The 5s
  // Playwright default proved too short when the machine is saturated (8 workers, each
  // with its own uvicorn + Chromium): a failing assertion was polled only 3 times in 5s.
  expect: { timeout: 10_000 },
  use: {
    headless: process.env.PLAYWRIGHT_HEADLESS !== '0',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
});