// Generated by GitHub Copilot
import type { Locator, Page } from '@playwright/test';

/** Encapsulates admin group creation interactions used by the E2E harness. */
export class AdminGroupsPage {
  readonly newGroupNameInput: Locator;
  readonly addGroupButton: Locator;

  constructor(private readonly page: Page) {
    this.newGroupNameInput = page.getByLabel('New group name');
    this.addGroupButton = page.getByRole('button', { name: 'Add Group' });
  }

  /** Navigates to the group administration page. */
  async goto(): Promise<void> {
    await this.page.goto('/admin/groups');
  }

  /** Creates a new group with the provided name. */
  async addGroup(groupName: string): Promise<void> {
    await this.newGroupNameInput.fill(groupName);
    await this.addGroupButton.click();
  }
}