// Generated by GitHub Copilot
import type { Locator, Page } from '@playwright/test';

/** Wraps entry detail interactions and stable locators used by the E2E tests. */
export class EntryDetailPage {
  readonly titleHeading: Locator;
  readonly editLink: Locator;

  constructor(private readonly page: Page) {
    this.titleHeading = page.getByRole('heading', { level: 1 });
    this.editLink = page.getByRole('link', { name: 'Edit' });
  }

  /** Returns the exact source link locator for a given URL. */
  sourceLink(url: string): Locator {
    return this.page.getByRole('link', { name: url, exact: true });
  }

  /** Returns a text locator scoped to the entry detail page. */
  text(value: string): Locator {
    return this.page.getByText(value);
  }

  /** Opens the entry edit form from the detail page. */
  async edit(): Promise<void> {
    await this.editLink.click();
  }
}