// Generated by GitHub Copilot
import type { Locator, Page } from '@playwright/test';

/** Represents the entry create/edit form used throughout the TypeScript E2E tests. */
export class EntryFormPage {
  readonly groupSelect: Locator;
  readonly yearInput: Locator;
  readonly monthInput: Locator;
  readonly dayInput: Locator;
  readonly titleInput: Locator;
  readonly sourceUrlInput: Locator;
  readonly eventSummaryInput: Locator;
  readonly tagsInput: Locator;
  readonly addLinkButton: Locator;
  readonly saveEntryButton: Locator;

  constructor(private readonly page: Page) {
    this.groupSelect = page.getByLabel('Timeline Group');
    this.yearInput = page.getByLabel('Year');
    this.monthInput = page.getByLabel('Month');
    this.dayInput = page.getByLabel('Day');
    this.titleInput = page.getByLabel('Title');
    this.sourceUrlInput = page.getByLabel('Source URL');
    this.eventSummaryInput = page.getByLabel('Event Summary');
    this.tagsInput = page.getByLabel('Tags');
    this.addLinkButton = page.getByRole('button', { name: 'Add Link' });
    this.saveEntryButton = page.getByRole('button', { name: 'Save Entry' });
  }

  /** Opens the new entry form. */
  async gotoNew(): Promise<void> {
    await this.page.goto('/entries/new');
  }

  /** Selects the timeline group. */
  async selectTimelineGroup(groupId: number | string): Promise<void> {
    await this.groupSelect.selectOption(`${groupId}`);
  }

  /** Fills the event date fields. */
  async fillDate(year: string, month: string, day: string): Promise<void> {
    await this.yearInput.fill(year);
    await this.monthInput.fill(month);
    await this.dayInput.fill(day);
  }

  /** Fills the entry title. */
  async fillTitle(title: string): Promise<void> {
    await this.titleInput.fill(title);
  }

  /** Fills the primary source URL. */
  async fillSourceUrl(sourceUrl: string): Promise<void> {
    await this.sourceUrlInput.fill(sourceUrl);
  }

  /** Adds a new link row to the form. */
  async addLinkRow(): Promise<void> {
    await this.addLinkButton.click();
  }

  /** Returns a specific link row locator. */
  linkRow(index: number): Locator {
    return this.page.locator('[data-link-row]').nth(index);
  }

  /** Fills a secondary link row. */
  async fillLinkRow(index: number, url: string, note: string): Promise<void> {
    const row = this.linkRow(index);
    await row.getByLabel('URL').fill(url);
    await row.getByLabel('Brief Note').fill(note);
  }

  /** Fills the event summary. */
  async fillEventSummary(summary: string): Promise<void> {
    await this.eventSummaryInput.fill(summary);
  }

  /** Fills the tags field. */
  async fillTags(tags: string): Promise<void> {
    await this.tagsInput.fill(tags);
  }

  /** Submits the entry form. */
  async save(): Promise<void> {
    await this.saveEntryButton.click();
  }
}