// Generated by GitHub Copilot
import type { Locator, Page } from '@playwright/test';

/** Encapsulates the search page controls and result locators. */
export class SearchPage {
  readonly searchHeading: Locator;
  readonly emptyStateHeading: Locator;
  readonly searchInput: Locator;
  readonly searchButton: Locator;
  readonly resultSummary: Locator;
  readonly createStoryLink: Locator;
  readonly filterTimelineLink: Locator;
  readonly clearSearchLink: Locator;

  constructor(private readonly page: Page) {
    this.searchHeading = page.getByRole('heading', { level: 1, name: 'Search Results' });
    this.emptyStateHeading = page.getByRole('heading', { level: 2, name: 'No search query yet' });
    this.searchInput = page.getByRole('searchbox', { name: 'Filter timeline in plain English' });
    this.searchButton = page.getByRole('button', { name: 'Search' });
    this.resultSummary = page.locator('[data-search-result-copy]');
    this.createStoryLink = page.getByRole('link', { name: 'Create story' });
    this.filterTimelineLink = page.getByRole('link', { name: 'Filter Timeline' });
    this.clearSearchLink = page.getByRole('link', { name: 'Clear search' });
  }

  /** Opens search for the selected group. */
  async goto(groupId: number | string): Promise<void> {
    await this.page.goto(`/search?group_id=${groupId}`);
  }

  /** Runs a search query using the page search controls. */
  async search(query: string): Promise<void> {
    await this.searchInput.fill(query);
    await this.searchButton.click();
  }

  /** Returns the first result card in the timeline results list. */
  firstResultCard(): Locator {
    return this.page.locator('.timeline-card').first();
  }

  /** Navigates from search results to the filtered timeline. */
  async openFilteredTimeline(): Promise<void> {
    await this.filterTimelineLink.click();
  }
}