// Generated by GitHub Copilot
import { test as base, expect, type BrowserContext } from '@playwright/test';
import { spawn, type ChildProcess } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { constants as fsConstants } from 'node:fs';
import { access, copyFile, mkdir, mkdtemp, readdir, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';
import { AdminGroupsPage } from '../poms/admin-groups-page.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '../../..');
const SOURCE_DB_PATH = resolve(REPO_ROOT, 'data', 'EventTracker.db');
const SQLITE_BRIDGE_PATH = resolve(__dirname, 'sqlite_bridge.py');
const SERVER_HOST = '127.0.0.1';
// Readiness is event-driven (uvicorn banner), so this is only a ceiling for loaded machines.
const SERVER_START_TIMEOUT_MS = 120_000;
const TEMP_DIR_PREFIX = 'eventtracker-playwright-ts-';
// Temp dirs younger than this may belong to a test still running in another
// worker (or another Playwright run), so cleanup must leave them alone.
const STALE_TEMP_DIR_AGE_MS = 60 * 60 * 1000;
const TEMP_DIR_CLEANUP_TIMEOUT_MS = 5_000;
const TEMP_DIR_CLEANUP_RETRY_INTERVAL_MS = 200;
const CSS_CACHE = new Map<string, string>();

export type AIProvider = 'openai' | 'copilot';

export interface E2ESession {
  baseURL: string;
  runId: string;
  groupName: string;
  dbPath: string;
  aiProvider: AIProvider;
}

type HarnessFixtures = {
  e2eSession: E2ESession;
  ensureDedicatedGroup: () => Promise<number>;
};

type ManagedServer = {
  process: ChildProcess;
  getOutput: () => string;
  /** Resolves with the bound port once uvicorn reports it is serving; rejects if it exits first. */
  ready: Promise<number>;
};

const READY_PATTERN = /Uvicorn running on http:\/\/[\d.]+:(\d+)/;

/**
 * Return a stable timestamp token suitable for database paths and group names.
 */
function createRunId(): string {
  const now = new Date();
  const parts = [
    now.getFullYear().toString(),
    `${now.getMonth() + 1}`.padStart(2, '0'),
    `${now.getDate()}`.padStart(2, '0'),
    `${now.getHours()}`.padStart(2, '0'),
    `${now.getMinutes()}`.padStart(2, '0'),
    `${now.getSeconds()}`.padStart(2, '0'),
    `${now.getMilliseconds()}`.padStart(3, '0'),
  ];
  return `${parts.join('')}-${randomUUID().slice(0, 8)}`;
}

/**
 * Return true when a filesystem path exists.
 */
async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await access(targetPath, fsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Copy the seed SQLite database into a temp location when the source database exists.
 */
async function copySeedDatabase(targetDbPath: string): Promise<void> {
  await mkdir(dirname(targetDbPath), { recursive: true });
  if (await pathExists(SOURCE_DB_PATH)) {
    await copyFile(SOURCE_DB_PATH, targetDbPath);
  }
}

/**
 * Build the environment for an isolated EventTracker server process.
 */
function buildServerEnv(dbPath: string, aiProvider: AIProvider): NodeJS.ProcessEnv {
  return {
    ...process.env,
    EVENTTRACKER_DB_PATH: dbPath,
    EVENTTRACKER_AI_PROVIDER: aiProvider,
    OPENAI_API_KEY: '',
    OPENAI_CHAT_MODEL_ID: '',
    OPENAI_BASE_URL: '',
    OPENAI_API_KEY_HEADER: '',
    OPENAI_EMBEDDING_MODEL_ID: '',
    COPILOT_CHAT_MODEL_ID: '',
    COPILOT_CLI_PATH: '',
    COPILOT_CLI_URL: '',
    PYTHONUNBUFFERED: '1',
    LOG_LEVEL: process.env.LOG_LEVEL ?? 'WARNING',
    // Each server would otherwise size native thread pools (OpenBLAS reserves
    // per-core buffers on import) to every core; with parallel workers that
    // exhausts memory and servers die before becoming ready.
    OPENBLAS_NUM_THREADS: '1',
    OMP_NUM_THREADS: '1',
    MKL_NUM_THREADS: '1',
  };
}

/**
 * Start an isolated uvicorn process on an OS-assigned port and capture its combined output.
 *
 * Binding port 0 lets the OS pick a free port atomically, avoiding the race between
 * probing for a free port and the server binding it. The actual port is parsed from
 * uvicorn's startup banner, which is only printed once application startup completes,
 * so no HTTP readiness polling is needed.
 */
function startServer(dbPath: string, aiProvider: AIProvider): ManagedServer {
  const serverProcess = spawn(
    'uv',
    [
      'run',
      'python',
      '-m',
      'uvicorn',
      'app.main:app',
      '--host',
      SERVER_HOST,
      '--port',
      '0',
      '--log-level',
      'info',
      '--no-access-log',
    ],
    {
      cwd: REPO_ROOT,
      env: buildServerEnv(dbPath, aiProvider),
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true,
    },
  );
  const outputChunks: Buffer[] = [];
  const getOutput = () => Buffer.concat(outputChunks).toString('utf8');

  const ready = new Promise<number>((resolveReady, rejectReady) => {
    let settled = false;
    const settle = (action: () => void) => {
      if (!settled) {
        settled = true;
        clearTimeout(timeoutHandle);
        action();
      }
    };
    const timeoutHandle = setTimeout(() => {
      settle(() =>
        rejectReady(
          new Error(
            `EventTracker server did not become ready within ${SERVER_START_TIMEOUT_MS / 1000} seconds.\nCaptured output:\n${getOutput()}`,
          ),
        ),
      );
    }, SERVER_START_TIMEOUT_MS);
    const onData = (chunk: Buffer) => {
      outputChunks.push(chunk);
      if (!settled) {
        const match = READY_PATTERN.exec(getOutput());
        if (match) {
          settle(() => resolveReady(Number(match[1])));
        }
      }
    };
    serverProcess.stdout.on('data', onData);
    serverProcess.stderr.on('data', onData);
    serverProcess.once('error', (error) => {
      settle(() => rejectReady(new Error(`EventTracker server failed to start: ${error.message}`)));
    });
    serverProcess.once('exit', () => {
      settle(() =>
        rejectReady(new Error(`EventTracker server exited before it became ready.\nCaptured output:\n${getOutput()}`)),
      );
    });
  });

  return { process: serverProcess, getOutput, ready };
}

/**
 * Wait for a child process to exit once a termination signal has been sent.
 */
async function waitForExit(serverProcess: ChildProcess, timeoutMs: number): Promise<boolean> {
  if (serverProcess.exitCode !== null) {
    return true;
  }

  return await new Promise<boolean>((resolveExit) => {
    const timeoutHandle = setTimeout(() => {
      serverProcess.off('exit', handleExit);
      resolveExit(false);
    }, timeoutMs);

    const handleExit = () => {
      clearTimeout(timeoutHandle);
      resolveExit(true);
    };

    serverProcess.once('exit', handleExit);
  });
}

/**
 * Stop an isolated EventTracker process without failing on already-closed handles.
 */
async function stopServer(serverProcess: ChildProcess): Promise<void> {
  if (serverProcess.exitCode === null && process.platform === 'win32' && serverProcess.pid !== undefined) {
    // On Windows, killing `uv run` (or the venv python.exe launcher) leaves the real
    // interpreter running as an orphan, so the whole process tree must be terminated.
    await killWindowsProcessTree(serverProcess.pid);
    await waitForExit(serverProcess, 10_000);
  }
  if (serverProcess.exitCode === null) {
    serverProcess.kill('SIGTERM');
    const exited = await waitForExit(serverProcess, 10_000);
    if (!exited && serverProcess.exitCode === null) {
      serverProcess.kill('SIGKILL');
      await waitForExit(serverProcess, 10_000);
    }
  }
}

/**
 * Terminate a Windows process and all of its descendants.
 */
async function killWindowsProcessTree(pid: number): Promise<void> {
  await new Promise<void>((resolveKill) => {
    const killer = spawn('taskkill', ['/PID', `${pid}`, '/T', '/F'], {
      stdio: 'ignore',
      windowsHide: true,
    });
    killer.once('error', () => resolveKill());
    killer.once('exit', () => resolveKill());
  });
}

/**
 * Return true when Windows reports a transient lock during temp directory cleanup.
 */
function isRetryableWindowsCleanupError(error: unknown): boolean {
  if (!(error instanceof Error)) {
    return false;
  }

  const code = (error as NodeJS.ErrnoException).code;
  return code === 'EBUSY' || code === 'EPERM' || code === 'ENOTEMPTY';
}

/**
 * Delete a temporary Playwright directory, retrying briefly for Windows file locks.
 */
async function removeTempDir(tempDir: string): Promise<void> {
  const deadline = Date.now() + TEMP_DIR_CLEANUP_TIMEOUT_MS;

  while (await pathExists(tempDir)) {
    try {
      await rm(tempDir, { recursive: true, force: true });
      return;
    } catch (error) {
      if (!isRetryableWindowsCleanupError(error)) {
        throw error;
      }
      if (Date.now() >= deadline) {
        return;
      }
      await delay(TEMP_DIR_CLEANUP_RETRY_INTERVAL_MS);
    }
  }
}

/**
 * Best-effort cleanup for stale TypeScript Playwright temp directories from prior runs.
 * Only directories older than STALE_TEMP_DIR_AGE_MS are removed so parallel workers
 * never delete each other's live databases.
 */
async function cleanupStaleTempDirs(): Promise<void> {
  const entries = await readdir(tmpdir(), { withFileTypes: true });
  const cutoff = Date.now() - STALE_TEMP_DIR_AGE_MS;
  await Promise.all(
    entries
      .filter((entry) => entry.isDirectory() && entry.name.startsWith(TEMP_DIR_PREFIX))
      .map(async (entry) => {
        const tempDir = join(tmpdir(), entry.name);
        try {
          if ((await stat(tempDir)).mtimeMs < cutoff) {
            await removeTempDir(tempDir);
          }
        } catch {
          // Another worker removed it first.
        }
      }),
  );
}

/**
 * Fetch a CDN stylesheet once per worker so local tests do not depend on repeated network fetches.
 */
async function fetchCdnStylesheet(url: string): Promise<string> {
  const cached = CSS_CACHE.get(url);
  if (cached !== undefined) {
    return cached;
  }

  try {
    const response = await fetch(url, { redirect: 'follow', signal: AbortSignal.timeout(10_000) });
    const body = response.ok ? await response.text() : '';
    CSS_CACHE.set(url, body);
    return body;
  } catch {
    CSS_CACHE.set(url, '');
    return '';
  }
}

/**
 * Wire the CDN stylesheet route so Playwright can render the Bootstrap UI consistently.
 */
async function attachStylesheetRoute(context: BrowserContext): Promise<void> {
  await context.route('**://cdn.jsdelivr.net/**', async (route) => {
    if (route.request().resourceType() !== 'stylesheet') {
      await route.abort();
      return;
    }

    await route.fulfill({
      status: 200,
      contentType: 'text/css',
      body: await fetchCdnStylesheet(route.request().url()),
    });
  });
}

/**
 * Query SQLite through Python's stdlib so the harness avoids a separate Node SQLite dependency.
 */
async function lookupGroupId(dbPath: string, groupName: string): Promise<number | null> {
  const bridgeProcess = spawn(
    'uv',
    ['run', 'python', SQLITE_BRIDGE_PATH, dbPath, groupName],
    {
      cwd: REPO_ROOT,
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true,
    },
  );
  const stdoutChunks: Buffer[] = [];
  const stderrChunks: Buffer[] = [];

  bridgeProcess.stdout.on('data', (chunk: Buffer) => {
    stdoutChunks.push(chunk);
  });
  bridgeProcess.stderr.on('data', (chunk: Buffer) => {
    stderrChunks.push(chunk);
  });

  const exitCode = await new Promise<number>((resolveExit, reject) => {
    bridgeProcess.once('error', reject);
    bridgeProcess.once('exit', (code) => {
      resolveExit(code ?? 1);
    });
  });

  if (exitCode !== 0) {
    throw new Error(Buffer.concat(stderrChunks).toString('utf8') || 'sqlite_bridge.py exited with an error.');
  }

  const stdout = Buffer.concat(stdoutChunks).toString('utf8').trim();
  if (stdout.length === 0) {
    return null;
  }

  const parsed = Number.parseInt(stdout, 10);
  return Number.isNaN(parsed) ? null : parsed;
}

/**
 * Build a Playwright test object whose fixtures launch EventTracker with the requested AI provider.
 */
function createHarnessTest(aiProvider: AIProvider) {
  return base.extend<HarnessFixtures>({
    e2eSession: async ({}, use) => {
      await cleanupStaleTempDirs();

      const runId = createRunId();
      const tempDir = await mkdtemp(join(tmpdir(), TEMP_DIR_PREFIX));
      const tempDbPath = join(tempDir, 'EventTracker-playwright.db');
      await copySeedDatabase(tempDbPath);

      const server = startServer(tempDbPath, aiProvider);

      try {
        const port = await server.ready;
        const baseURL = `http://${SERVER_HOST}:${port}`;
        await use({
          baseURL,
          runId,
          groupName: `Playwright E2E ${runId}`,
          dbPath: tempDbPath,
          aiProvider,
        });
      } finally {
        await stopServer(server.process);
        await removeTempDir(tempDir);
      }
    },

    context: async ({ browser, e2eSession }, use) => {
      const context = await browser.newContext({
        baseURL: e2eSession.baseURL,
        acceptDownloads: true,
        viewport: { width: 1440, height: 1100 },
      });
      await attachStylesheetRoute(context);

      try {
        await use(context);
      } finally {
        await context.close();
      }
    },

    page: async ({ context }, use) => {
      const page = await context.newPage();
      page.setDefaultTimeout(10_000);
      await use(page);
    },

    ensureDedicatedGroup: async ({ page, e2eSession }, use) => {
      await use(async () => {
        const existingGroupId = await lookupGroupId(e2eSession.dbPath, e2eSession.groupName);
        if (existingGroupId !== null) {
          return existingGroupId;
        }

        const adminGroupsPage = new AdminGroupsPage(page);
        await adminGroupsPage.goto();
        await adminGroupsPage.addGroup(e2eSession.groupName);
        await expect(page).toHaveURL(/\/admin\/groups\?notice=created$/);

        const createdGroupId = await lookupGroupId(e2eSession.dbPath, e2eSession.groupName);
        if (createdGroupId === null) {
          throw new Error(`Expected dedicated test group ${e2eSession.groupName} to exist after creation.`);
        }
        return createdGroupId;
      });
    },
  });
}

export const test = createHarnessTest('openai');
export const copilotTest = createHarnessTest('copilot');
export { expect };