# Generated by GitHub Copilot
from __future__ import annotations

import sqlite3
import sys


def lookup_group_id(db_path: str, group_name: str) -> int | None:
    """Return the timeline group id for a name, or None when no match exists."""
    with sqlite3.connect(db_path) as connection:
        row = connection.execute(
            "SELECT id FROM timeline_groups WHERE name = ?",
            (group_name,),
        ).fetchone()
    return int(row[0]) if row else None


def main(argv: list[str]) -> int:
    """Read bridge arguments, print the matching group id when present, and exit."""
    if len(argv) != 2:
        raise SystemExit("usage: sqlite_bridge.py <db-path> <group-name>")

    db_path, group_name = argv
    group_id = lookup_group_id(db_path, group_name)
    if group_id is not None:
        print(group_id)
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))