from __future__ import annotations

from collections.abc import Awaitable, Iterable
from contextlib import AbstractAsyncContextManager, AsyncExitStack
from dataclasses import dataclass
from functools import lru_cache
from inspect import Parameter, isawaitable, signature
import logging
import re
from typing import Any, Callable, Protocol, TypeVar, cast


COPILOT_SDK_REQUIRED_MESSAGE = (
    "GitHub Copilot draft generation requires the github-copilot-sdk package."
)
COPILOT_CLIENT_SETTINGS_MESSAGE = (
    "Unable to initialize the GitHub Copilot client with the current settings. "
    "Most setups should leave COPILOT_CLI_PATH and COPILOT_CLI_URL unset."
)
logger = logging.getLogger(__name__)
_COPILOT_MODEL_ID_RE = re.compile(
    r"^(?P<family>[a-z]+(?:-[a-z]+)*-\d+)(?:\.(?P<version>\d+(?:\.\d+)*))?(?P<suffix>(?:-[a-z0-9]+)*)$",
    re.IGNORECASE,
)


class CopilotClientSettings(Protocol):
    @property
    def cli_path(self) -> str | None: ...

    @property
    def cli_url(self) -> str | None: ...


class CopilotSession(Protocol):
    async def send_and_wait(
        self, payload: dict[str, str], timeout: float
    ) -> object: ...

    def on(self, handler: Callable[[object], None]) -> Callable[[], None] | None: ...

    async def close(self) -> None: ...

    async def disconnect(self) -> None: ...


class CopilotClient(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def create_session(self, config: dict[str, object]) -> CopilotSession: ...


class CopilotClientConstructor(Protocol):
    def __call__(self, options: dict[str, str] | None = None) -> CopilotClient: ...


class CopilotPermissionHandler(Protocol):
    approve_all: object


class CopilotSdkModule(Protocol):
    CopilotClient: CopilotClientConstructor
    PermissionHandler: CopilotPermissionHandler


class SupportsAsyncStartStop(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...


class SupportsAsyncClose(Protocol):
    async def close(self) -> None: ...


class SupportsAsyncDisconnect(Protocol):
    async def disconnect(self) -> None: ...


TClient = TypeVar("TClient")
TResource = TypeVar("TResource")


@dataclass(frozen=True, slots=True)
class _ParsedCopilotModelId:
    family: str
    version: tuple[int, ...]
    suffix: str


@lru_cache(maxsize=1)
def load_copilot_sdk() -> CopilotSdkModule:
    from app.services import copilot_sdk

    return cast(CopilotSdkModule, copilot_sdk)


def instantiate_copilot_client(
    settings: CopilotClientSettings,
    *,
    configuration_error_type: type[Exception],
    missing_sdk_message: str,
    invalid_settings_message: str,
) -> CopilotClient:
    try:
        client_class = load_copilot_sdk().CopilotClient
    except ModuleNotFoundError as exc:
        if exc.name not in {"github_copilot_sdk", "copilot"}:
            raise
        raise configuration_error_type(missing_sdk_message) from exc

    options = {
        "cli_path": settings.cli_path,
        "cli_url": settings.cli_url,
    }
    filtered_options = {
        key: value for key, value in options.items() if value is not None
    }
    try:
        return client_class(filtered_options or None)
    except (TypeError, ValueError) as exc:
        raise configuration_error_type(invalid_settings_message) from exc


def get_permission_handler() -> object:
    return load_copilot_sdk().PermissionHandler.approve_all


# Generated by GitHub Copilot
def _parse_copilot_model_id(model_id: str) -> _ParsedCopilotModelId | None:
    """Parse a Copilot model id into family, version, and suffix parts."""
    normalized_model_id = model_id.strip().lower()
    if not normalized_model_id:
        return None

    match = _COPILOT_MODEL_ID_RE.fullmatch(normalized_model_id)
    if match is None:
        return None

    version_text = match.group("version") or ""
    version = tuple(int(part) for part in version_text.split(".")) if version_text else ()
    return _ParsedCopilotModelId(
        family=match.group("family"),
        version=version,
        suffix=match.group("suffix") or "",
    )


def _select_best_available_copilot_model_id(
    requested_model_id: str,
    available_model_ids: tuple[str, ...],
) -> str | None:
    """Choose the closest available model within the requested runtime family."""
    normalized_requested_model_id = requested_model_id.strip().lower()
    if not normalized_requested_model_id:
        return None

    for candidate_model_id in available_model_ids:
        if candidate_model_id.lower() == normalized_requested_model_id:
            return candidate_model_id

    requested_model = _parse_copilot_model_id(normalized_requested_model_id)
    if requested_model is None:
        return None

    same_family_candidates: list[tuple[str, _ParsedCopilotModelId]] = []
    exact_suffix_candidates: list[tuple[str, _ParsedCopilotModelId]] = []
    suffixless_candidates: list[tuple[str, _ParsedCopilotModelId]] = []
    for candidate_model_id in available_model_ids:
        parsed_candidate = _parse_copilot_model_id(candidate_model_id)
        if parsed_candidate is None or parsed_candidate.family != requested_model.family:
            continue
        candidate_entry = (candidate_model_id, parsed_candidate)
        same_family_candidates.append(candidate_entry)
        if parsed_candidate.suffix == requested_model.suffix:
            exact_suffix_candidates.append(candidate_entry)
        if not parsed_candidate.suffix:
            suffixless_candidates.append(candidate_entry)

    ranked_candidates = same_family_candidates
    if requested_model.suffix and exact_suffix_candidates:
        ranked_candidates = exact_suffix_candidates
    elif not requested_model.suffix and suffixless_candidates:
        ranked_candidates = suffixless_candidates

    if not ranked_candidates:
        return None

    ranked_candidates.sort(
        key=lambda item: (item[1].version, -len(item[1].suffix), item[0].lower()),
        reverse=True,
    )
    return ranked_candidates[0][0]


async def _list_available_copilot_model_ids(client: CopilotClient) -> tuple[str, ...]:
    """Return model ids exposed by the active Copilot runtime, if available."""
    list_models = getattr(client, "list_models", None)
    if not callable(list_models):
        return ()

    try:
        models_result = list_models()
        if isawaitable(models_result):
            models_object = await cast(Awaitable[object], models_result)
        else:
            models_object = models_result
    except Exception:
        logger.debug(
            "Unable to list Copilot models before creating a session.",
            exc_info=True,
        )
        return ()

    if not isinstance(models_object, Iterable):
        return ()

    model_ids: list[str] = []
    for model in models_object:
        model_id = getattr(model, "id", None)
        if not isinstance(model_id, str):
            continue
        normalized_model_id = model_id.strip()
        if normalized_model_id:
            model_ids.append(normalized_model_id)
    return tuple(model_ids)


async def resolve_copilot_model_id(
    client: CopilotClient,
    requested_model_id: str,
) -> str:
    """Resolve stale or versionless model ids to a supported runtime model id."""
    normalized_requested_model_id = requested_model_id.strip()
    if not normalized_requested_model_id:
        return requested_model_id

    available_model_ids = await _list_available_copilot_model_ids(client)
    resolved_model_id = _select_best_available_copilot_model_id(
        normalized_requested_model_id,
        available_model_ids,
    )
    if resolved_model_id is None:
        return normalized_requested_model_id
    if resolved_model_id.lower() != normalized_requested_model_id.lower():
        logger.warning(
            "Configured Copilot model '%s' is unavailable. Falling back to '%s'.",
            normalized_requested_model_id,
            resolved_model_id,
        )
    return resolved_model_id


async def create_copilot_session(
    client: CopilotClient,
    *,
    model_id: str,
    system_message: str,
    reasoning_effort: str | None = None,
    streaming: bool = False,
) -> CopilotSession:
    resolved_model_id = await resolve_copilot_model_id(client, model_id)
    config: dict[str, object] = {
        "model": resolved_model_id,
        "on_permission_request": get_permission_handler(),
        "system_message": {
            "mode": "append",
            "content": system_message,
        },
    }
    if reasoning_effort is not None:
        config["reasoning_effort"] = reasoning_effort
    if streaming:
        config["streaming"] = True

    create_session = cast(Any, client).create_session
    try:
        parameters = tuple(signature(create_session).parameters.values())
    except (TypeError, ValueError):
        parameters = ()

    supports_keyword_config = any(
        parameter.kind in (Parameter.KEYWORD_ONLY, Parameter.VAR_KEYWORD)
        for parameter in parameters
    )
    if supports_keyword_config:
        return await create_session(**config)
    return await create_session(config)


async def prepare_copilot_client(
    exit_stack: AsyncExitStack,
    client: TClient,
) -> TClient:
    enter_async = getattr(client, "__aenter__", None)
    exit_async = getattr(client, "__aexit__", None)
    if callable(enter_async) and callable(exit_async):
        context_manager = cast(AbstractAsyncContextManager[TClient], client)
        return await exit_stack.enter_async_context(context_manager)

    start = getattr(client, "start", None)
    stop = getattr(client, "stop", None)
    if callable(start) and callable(stop):
        lifecycle_client = cast(SupportsAsyncStartStop, client)
        await lifecycle_client.start()
        exit_stack.push_async_callback(lifecycle_client.stop)
        return client

    raise TypeError(
        "Copilot client does not support async context management or start/stop lifecycle."
    )


async def prepare_copilot_resource(
    exit_stack: AsyncExitStack,
    resource: TResource,
) -> TResource:
    close = getattr(resource, "close", None)
    if callable(close):
        closeable_resource = cast(SupportsAsyncClose, resource)
        exit_stack.push_async_callback(closeable_resource.close)
        return resource

    disconnect = getattr(resource, "disconnect", None)
    if callable(disconnect):
        disconnectable_resource = cast(SupportsAsyncDisconnect, resource)
        exit_stack.push_async_callback(disconnectable_resource.disconnect)
        return resource

    raise TypeError(
        "Copilot resource does not support close or disconnect lifecycle methods."
    )


async def send_copilot_prompt(
    session: CopilotSession, prompt: str, *, timeout: float
) -> object:
    send_and_wait = cast(Any, session).send_and_wait
    try:
        parameters = tuple(signature(send_and_wait).parameters.values())
    except (TypeError, ValueError):
        parameters = ()

    if parameters:
        if parameters[0].name == "prompt":
            return await send_and_wait(prompt, timeout=timeout)
        return await send_and_wait({"prompt": prompt}, timeout)

    try:
        return await send_and_wait(prompt, timeout=timeout)
    except TypeError:
        return await send_and_wait({"prompt": prompt}, timeout)


def extract_copilot_message_content(response: object) -> str:
    if response is None:
        return ""
    if isinstance(response, str):
        return response
    if isinstance(response, dict):
        for key in ("content", "text", "message", "response", "output", "data"):
            extracted = extract_copilot_message_content(response.get(key))
            if extracted:
                return extracted
        for key in ("messages", "events", "items"):
            items = response.get(key)
            if isinstance(items, list):
                for item in reversed(items):
                    extracted = extract_copilot_message_content(item)
                    if extracted:
                        return extracted
        return ""
    if isinstance(response, (list, tuple)):
        for item in reversed(response):
            extracted = extract_copilot_message_content(item)
            if extracted:
                return extracted
        return ""

    for attr_name in ("content", "text", "message", "response", "output", "data"):
        if hasattr(response, attr_name):
            extracted = extract_copilot_message_content(getattr(response, attr_name))
            if extracted:
                return extracted
    return ""


def subscribe_to_session_events(
    session: CopilotSession,
    handler: Callable[[object], None] | None,
) -> Callable[[], None]:
    if handler is None:
        return lambda: None

    try:
        on_method = session.on
    except AttributeError:
        return lambda: None

    unsubscribe = on_method(handler)
    if callable(unsubscribe):
        return unsubscribe
    return lambda: None
