// Generated by GitHub Copilot
import type { Locator, Page } from '@playwright/test';

/** Encapsulates timeline navigation and view controls used by the E2E scenarios. */
export class TimelinePage {
  readonly eventsLink: Locator;
  readonly exportLink: Locator;
  readonly adminLink: Locator;
  readonly newEntryLink: Locator;
  readonly heading: Locator;
  readonly groupValue: Locator;
  readonly viewControls: Locator;
  readonly detailsButton: Locator;
  readonly summariesButton: Locator;
  readonly monthsButton: Locator;
  readonly currentViewLabel: Locator;

  constructor(private readonly page: Page) {
    this.eventsLink = page.getByRole('link', { name: 'Events' });
    this.exportLink = page.getByRole('link', { name: 'Export' });
    this.adminLink = page.getByRole('link', { name: 'Admin' });
    this.newEntryLink = page.getByRole('link', { name: 'New Entry' });
    this.heading = page.getByRole('heading', { level: 1 });
    this.groupValue = page.locator('.group-flyout-value');
    this.viewControls = page.getByRole('group', { name: 'Timeline views' });
    this.detailsButton = this.viewControls.getByRole('button', { name: 'Details', exact: true });
    this.summariesButton = this.viewControls.getByRole('button', { name: 'Summaries', exact: true });
    this.monthsButton = this.viewControls.getByRole('button', { name: 'Months', exact: true });
    this.currentViewLabel = page.locator('[data-current-view-label]');
  }

  /** Opens the timeline for the selected group. */
  async goto(groupId: number | string): Promise<void> {
    await this.page.goto(`/?group_id=${groupId}`);
  }

  /** Switches the timeline into the months view. */
  async showMonths(): Promise<void> {
    await this.monthsButton.click();
  }

  /** Switches the timeline into the summaries view. */
  async showSummaries(): Promise<void> {
    await this.summariesButton.click();
  }

  /** Returns the first month drill-view bucket. */
  firstMonthBucket(): Locator {
    return this.page.locator('[data-drill-view]').first();
  }

  /** Returns the first open drill-in button. */
  firstOpenButton(): Locator {
    return this.page.getByRole('button', { name: /^Open / }).first();
  }

  /** Returns the first start-story link. */
  firstStartStoryLink(): Locator {
    return this.page.getByRole('link', { name: 'Start story' }).first();
  }
}