"""Generate a self-contained HTML e2e test report with embedded screenshots."""
# Generated by GitHub Copilot
from __future__ import annotations

import base64
from dataclasses import dataclass
from html import escape
import re
from pathlib import Path
import xml.etree.ElementTree as ET

SCREENSHOTS_DIR = Path(__file__).resolve().parents[1] / "test-screenshots"
# Generated by GitHub Copilot
TEST_REPORTS_DIR = Path(__file__).resolve().parents[1] / "docs" / "test-reports"
TEST_REPORTS_DIR.mkdir(parents=True, exist_ok=True)

REPORT_PATH = TEST_REPORTS_DIR / "test-report.html"
RESULTS_PATH = TEST_REPORTS_DIR / "test-results-e2e.xml"


@dataclass(frozen=True, slots=True)
class TestResult:
    """Represents one executed e2e test case and its report metadata."""

    module: str
    name: str
    status: str
    duration_seconds: float
    details: str


def _safe_screenshot_name(module: str, test_name: str) -> str:
    """Match the e2e fixture's screenshot file naming logic."""
    node_id = f"{module}::{test_name}"
    return re.sub(r"[^\w\-]", "_", node_id)[:120]


def _find_screenshot(module: str, test_name: str) -> str | None:
    """Return a base64 data URI for the test screenshot when it exists."""
    screenshot_path = SCREENSHOTS_DIR / f"{_safe_screenshot_name(module, test_name)}.png"
    if not screenshot_path.exists():
        return None
    data = base64.b64encode(screenshot_path.read_bytes()).decode("ascii")
    return f"data:image/png;base64,{data}"


def _module_from_classname(classname: str) -> str:
    """Convert pytest's dotted classname into a workspace-relative module path."""
    return f"{classname.replace('.', '/')}.py"


def _status_from_case(case: ET.Element) -> tuple[str, str]:
    """Classify a JUnit testcase using pytest's child nodes."""
    if (error := case.find("error")) is not None:
        return "ERROR", (error.get("message") or error.text or "").strip()
    if (failure := case.find("failure")) is not None:
        return "FAILED", (failure.get("message") or failure.text or "").strip()
    if (skipped := case.find("skipped")) is not None:
        return "SKIPPED", (skipped.get("message") or skipped.text or "").strip()
    return "PASSED", ""


def _load_results(results_path: Path) -> tuple[list[TestResult], ET.Element]:
    """Load structured test results from a JUnit XML file."""
    root = ET.fromstring(results_path.read_text(encoding="utf-8"))
    suite = root.find("testsuite") if root.tag == "testsuites" else root
    if suite is None:
        raise ValueError(f"No testsuite found in {results_path}")

    results: list[TestResult] = []
    for case in suite.findall("testcase"):
        classname = case.get("classname", "")
        module = _module_from_classname(classname) if classname else "unknown"
        name = case.get("name", "unknown")
        status, details = _status_from_case(case)
        duration_seconds = float(case.get("time", "0") or "0")
        results.append(
            TestResult(
                module=module,
                name=name,
                status=status,
                duration_seconds=duration_seconds,
                details=details,
            )
        )
    return results, suite


def _build_row(result: TestResult) -> str:
    """Render one HTML table row for a test result."""
    color_map = {
        "PASSED": "#2e7d32",
        "FAILED": "#c62828",
        "ERROR": "#ad1457",
        "SKIPPED": "#6d4c41",
    }
    icon_map = {
        "PASSED": "\u2705",
        "FAILED": "\u274c",
        "ERROR": "\u26a0\ufe0f",
        "SKIPPED": "\u23ed\ufe0f",
    }
    short_module = result.module.split("/")[-1].replace(".py", "")
    color = color_map.get(result.status, "#37474f")
    icon = icon_map.get(result.status, "\u2022")
    img_src = _find_screenshot(result.module, result.name)
    if img_src:
        img_html = (
            '<img src="' + img_src + '" alt="end-of-test screenshot" '
            'style="max-width:100%;border:1px solid #ddd;border-radius:4px;'
            'margin-top:10px;cursor:zoom-in" '
            'onclick="this.style.maxWidth=this.style.maxWidth===\'100%\'?\'none\':\'100%\'" />'
        )
    else:
        img_html = '<span style="color:#888;font-style:italic">no screenshot captured</span>'

    details_html = ""
    if result.details:
        details_html = (
            '<details style="margin-top:10px">'
            '<summary style="cursor:pointer">Details</summary>'
            f'<pre style="white-space:pre-wrap;font-size:.82rem;margin:8px 0 0">{escape(result.details)}</pre>'
            '</details>'
        )

    return (
        "<tr>"
        f'<td style="padding:8px 12px;color:{color};white-space:nowrap">{icon} {result.status}</td>'
        f'<td style="padding:8px 12px;color:#555;font-size:.85em;white-space:nowrap">{escape(short_module)}</td>'
        f'<td style="padding:8px 12px;font-family:monospace;font-size:.88em;word-break:break-all">{escape(result.name)}</td>'
        f'<td style="padding:8px 12px;white-space:nowrap">{result.duration_seconds:.2f}s</td>'
        f'<td style="padding:8px 12px;min-width:320px">{img_html}{details_html}</td>'
        "</tr>"
    )


def main() -> None:
    """Build the HTML report from the latest JUnit XML output."""
    results, suite = _load_results(RESULTS_PATH)
    total = len(results)
    passed = sum(1 for result in results if result.status == "PASSED")
    failed = sum(1 for result in results if result.status == "FAILED")
    errors = sum(1 for result in results if result.status == "ERROR")
    skipped = sum(1 for result in results if result.status == "SKIPPED")
    runtime = float(suite.get("time", "0") or "0")
    timestamp = suite.get("timestamp", "unknown")

    rows = "\n".join(_build_row(result) for result in results)

    summary_badges = [
        f'<span class="badge b-total">{total} total</span>',
        f'<span class="badge b-pass">{passed} passed</span>',
    ]
    if failed:
        summary_badges.append(f'<span class="badge b-fail">{failed} failed</span>')
    if errors:
        summary_badges.append(f'<span class="badge b-error">{errors} errors</span>')
    if skipped:
        summary_badges.append(f'<span class="badge b-skip">{skipped} skipped</span>')

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>EventTracker \u2014 Playwright E2E Test Report</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; }}
  body {{ font-family: system-ui, -apple-system, sans-serif; margin: 0; background: #f5f7fa; color: #212121; }}
  header {{ background: #1a237e; color: #fff; padding: 24px 32px; }}
  header h1 {{ margin: 0; font-size: 1.4rem; font-weight: 700; }}
  header p {{ margin: 6px 0 0; opacity: .82; font-size: .88rem; }}
  .summary {{ display: flex; gap: 16px; padding: 16px 32px; background: #fff; border-bottom: 1px solid #e0e0e0; flex-wrap: wrap; }}
  .badge {{ padding: 6px 16px; border-radius: 20px; font-weight: 700; font-size: .9rem; }}
  .b-total {{ background: #e3f2fd; color: #1565c0; }}
  .b-pass {{ background: #e8f5e9; color: #2e7d32; }}
  .b-fail {{ background: #ffebee; color: #c62828; }}
  .b-error {{ background: #fce4ec; color: #ad1457; }}
  .b-skip {{ background: #efebe9; color: #6d4c41; }}
  .container {{ padding: 24px 32px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden;
           box-shadow: 0 1px 4px rgba(0,0,0,.1); }}
  thead {{ background: #e8eaf6; }}
  th {{ text-align: left; padding: 10px 12px; font-size: .82rem; color: #37474f; font-weight: 600;
        text-transform: uppercase; letter-spacing: .04em; }}
  tbody tr:nth-child(even) {{ background: #fafafa; }}
  tbody tr:hover {{ background: #f0f4ff; }}
  td {{ vertical-align: top; border-top: 1px solid #eeeeee; }}
  footer {{ text-align: center; padding: 16px; color: #9e9e9e; font-size: .8rem; }}
</style>
</head>
<body>
<header>
  <h1>EventTracker \u2014 Playwright E2E Test Report</h1>
  <p>JUnit source: {escape(RESULTS_PATH.name)} &nbsp;&bull;&nbsp; Timestamp: {escape(timestamp)} &nbsp;&bull;&nbsp; Runtime: {runtime:.2f}s</p>
</header>
<div class="summary">
  {' '.join(summary_badges)}
</div>
<div class="container">
  <table>
    <thead>
      <tr>
        <th>Result</th>
        <th>Module</th>
        <th>Test ID</th>
        <th>Duration</th>
        <th>Screenshot / Details</th>
      </tr>
    </thead>
    <tbody>
{rows}
    </tbody>
  </table>
</div>
<footer>Generated from the latest Playwright pytest JUnit XML output</footer>
</body>
</html>"""

    REPORT_PATH.write_text(html, encoding="utf-8")
    print(f"Report written to {REPORT_PATH} ({REPORT_PATH.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
