#Requires -Version 7.0
<#
.SYNOPSIS
Syncs the factory's master agents and skills into .claude/ and .agents/.

.DESCRIPTION
my-factory/agents/*.md and my-factory/skills/<name>/ are the only copies you edit.
This script mirrors them into .claude/agents, .claude/skills, .agents/agents, and .agents/skills,
stamps every generated Markdown file with a do-not-edit marker, and removes my-factory* items
that no longer exist in the master set. Items without the my-factory prefix are never touched.

.PARAMETER Check
Report drift and exit 1 without writing anything.

.EXAMPLE
pwsh -File my-factory/sync.ps1
pwsh -File my-factory/sync.ps1 -Check
#>
[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Prefix = 'my-factory'
$FactoryDir = $PSScriptRoot
$RepoRoot = Split-Path $FactoryDir -Parent
$Targets = @('.claude', '.agents')
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Get-RepoPath([string]$Path) {
    [IO.Path]::GetRelativePath($RepoRoot, $Path) -replace '\\', '/'
}

function Get-FrontmatterName([string]$Text) {
    if ($Text -notmatch '(?s)^---\r?\n(.*?)\r?\n---') { return $null }
    $frontmatter = $Matches[1]
    if ($frontmatter -match '(?m)^name:\s*(\S+)\s*$') { return $Matches[1] }
    return $null
}

# Markdown copies get a marker after the frontmatter so nobody edits them by mistake.
# Other files are copied byte for byte.
function Get-GeneratedBytes([string]$SourcePath) {
    if ([IO.Path]::GetExtension($SourcePath) -ne '.md') {
        return [IO.File]::ReadAllBytes($SourcePath)
    }
    $text = [IO.File]::ReadAllText($SourcePath)
    $newline = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }
    $marker = "<!-- Generated by my-factory/sync.ps1 from $(Get-RepoPath $SourcePath). Edit that file, then re-run the sync. -->"
    if ($text -match '(?s)^(---\r?\n.*?\r?\n---\r?\n)') {
        $head = $Matches[1]
        $text = $head + $marker + $newline + $text.Substring($head.Length)
    } else {
        $text = $marker + $newline + $newline + $text
    }
    return $Utf8NoBom.GetBytes($text)
}

# ---------- collect and validate the master set ----------

$problems = [Collections.Generic.List[string]]::new()
$desired = [ordered]@{}   # repo-relative target path -> source path

$agentsDir = Join-Path $FactoryDir 'agents'
$skillsDir = Join-Path $FactoryDir 'skills'

$agents = @(if (Test-Path $agentsDir) { Get-ChildItem $agentsDir -File -Filter '*.md' })
foreach ($agent in $agents) {
    $name = $agent.BaseName
    if (-not $name.StartsWith($Prefix)) { $problems.Add("$(Get-RepoPath $agent.FullName): file name must start with '$Prefix'") }
    $declared = Get-FrontmatterName ([IO.File]::ReadAllText($agent.FullName))
    if ($declared -ne $name) { $problems.Add("$(Get-RepoPath $agent.FullName): frontmatter name '$declared' must equal '$name'") }
    foreach ($target in $Targets) { $desired["$target/agents/$($agent.Name)"] = $agent.FullName }
}

$skills = @(if (Test-Path $skillsDir) { Get-ChildItem $skillsDir -Directory })
foreach ($skill in $skills) {
    $name = $skill.Name
    if (-not $name.StartsWith($Prefix)) { $problems.Add("$(Get-RepoPath $skill.FullName): folder name must start with '$Prefix'") }
    $skillFile = Join-Path $skill.FullName 'SKILL.md'
    if (-not (Test-Path $skillFile)) {
        $problems.Add("$(Get-RepoPath $skill.FullName): missing SKILL.md")
    } else {
        $declared = Get-FrontmatterName ([IO.File]::ReadAllText($skillFile))
        if ($declared -ne $name) { $problems.Add("$(Get-RepoPath $skillFile): frontmatter name '$declared' must equal '$name'") }
    }
    foreach ($file in Get-ChildItem $skill.FullName -File -Recurse) {
        $relative = [IO.Path]::GetRelativePath($skill.FullName, $file.FullName) -replace '\\', '/'
        foreach ($target in $Targets) { $desired["$target/skills/$name/$relative"] = $file.FullName }
    }
}

if ($problems.Count) {
    $problems | ForEach-Object { Write-Host "error: $_" -ForegroundColor Red }
    exit 2
}

# ---------- what the targets hold today (only my-factory* items) ----------

$existing = [Collections.Generic.List[string]]::new()
foreach ($target in $Targets) {
    $targetAgents = Join-Path $RepoRoot "$target/agents"
    if (Test-Path $targetAgents) {
        Get-ChildItem $targetAgents -File -Filter "$Prefix*.md" | ForEach-Object { $existing.Add((Get-RepoPath $_.FullName)) }
    }
    $targetSkills = Join-Path $RepoRoot "$target/skills"
    if (Test-Path $targetSkills) {
        Get-ChildItem $targetSkills -Directory -Filter "$Prefix*" |
            Get-ChildItem -File -Recurse | ForEach-Object { $existing.Add((Get-RepoPath $_.FullName)) }
    }
}

# ---------- apply or check ----------

$written = 0; $removed = 0; $unchanged = 0

foreach ($entry in $desired.GetEnumerator()) {
    $path = Join-Path $RepoRoot $entry.Key
    $bytes = Get-GeneratedBytes $entry.Value
    if ((Test-Path $path) -and [Linq.Enumerable]::SequenceEqual([byte[]][IO.File]::ReadAllBytes($path), [byte[]]$bytes)) {
        $unchanged++
        continue
    }
    $written++
    if ($Check) { Write-Host "out of date: $($entry.Key)"; continue }
    New-Item -ItemType Directory -Force (Split-Path $path -Parent) | Out-Null
    [IO.File]::WriteAllBytes($path, $bytes)
    Write-Host "wrote:   $($entry.Key)"
}

foreach ($stale in $existing | Where-Object { -not $desired.Contains($_) }) {
    $removed++
    if ($Check) { Write-Host "stale:       $stale"; continue }
    Remove-Item (Join-Path $RepoRoot $stale) -Force
    Write-Host "removed: $stale"
}

if (-not $Check) {
    # Drop my-factory* skill folders left empty by removals.
    foreach ($target in $Targets) {
        $targetSkills = Join-Path $RepoRoot "$target/skills"
        if (-not (Test-Path $targetSkills)) { continue }
        Get-ChildItem $targetSkills -Directory -Filter "$Prefix*" |
            Get-ChildItem -Directory -Recurse | Sort-Object { $_.FullName.Length } -Descending |
            Where-Object { -not (Get-ChildItem $_.FullName -Force) } | Remove-Item -Force
        Get-ChildItem $targetSkills -Directory -Filter "$Prefix*" |
            Where-Object { -not (Get-ChildItem $_.FullName -Force) } | Remove-Item -Force
    }
}

$verb = if ($Check) { 'to update' } else { 'written' }
Write-Host "$($agents.Count) agents, $($skills.Count) skills -> $($Targets -join ', '): $written $verb, $removed $(if ($Check) { 'to remove' } else { 'removed' }), $unchanged unchanged"
if ($Check -and ($written -or $removed)) { exit 1 }
