// Generated by GitHub Copilot
// Scenario 3: Entry lifecycle from create to read to edit
// 1. Open /entries/new.
// 2. Fill the required fields with unique test data.
// 3. Add one additional link row with a note.
// 4. Enter tags and a simple summary directly rather than depending on AI generation.
// 5. Save the entry.
// 6. Assert redirect to the entry detail page and verify the title, date, tags, and link are visible.
// 7. Click Edit.
// 8. Change the title or tags and save again.
// 9. Assert the detail page reflects the updated value.

import { expect, test } from './helpers/harness.js';
import { EntryDetailPage } from './poms/entry-detail-page.js';
import { EntryFormPage } from './poms/entry-form-page.js';

test('scenario 3: create, view, and edit an entry', async ({ ensureDedicatedGroup, page }) => {
  const groupId = await ensureDedicatedGroup();
  const uniqueSuffix = `${Date.now()}`;
  const title = `Scenario 3 Entry ${uniqueSuffix}`;
  const updatedTitle = `${title} Updated`;
  const sourceUrl = `https://example.com/${uniqueSuffix}`;
  const extraUrl = `https://example.com/${uniqueSuffix}/reference`;
  const entryFormPage = new EntryFormPage(page);
  const entryDetailPage = new EntryDetailPage(page);

  await entryFormPage.gotoNew();

  await entryFormPage.selectTimelineGroup(groupId);
  await entryFormPage.fillDate('2026', '4', '2');
  await entryFormPage.fillTitle(title);
  await entryFormPage.fillSourceUrl(sourceUrl);
  await entryFormPage.addLinkRow();

  await entryFormPage.fillLinkRow(1, extraUrl, 'Supporting reference');

  await entryFormPage.fillEventSummary('<b>Scenario 3 summary</b> captured through Playwright CLI.');
  await entryFormPage.fillTags('scenario-3, playwright-cli');
  await entryFormPage.save();

  await expect(page).toHaveURL(/\/entries\/\d+\/view$/);
  await expect(entryDetailPage.titleHeading).toHaveText(title);
  await expect(entryDetailPage.sourceLink(sourceUrl)).toBeVisible();
  await expect(entryDetailPage.sourceLink(extraUrl)).toBeVisible();
  await expect(entryDetailPage.text('Supporting reference')).toBeVisible();
  await expect(entryDetailPage.text('scenario-3')).toBeVisible();
  await expect(entryDetailPage.text('playwright-cli')).toBeVisible();

  await entryDetailPage.edit();
  await expect(page).toHaveURL(/\/entries\/\d+$/);
  await entryFormPage.fillTitle(updatedTitle);
  await entryFormPage.fillTags('scenario-3, playwright-updated');
  await entryFormPage.save();

  await expect(page).toHaveURL(/\/entries\/\d+\/view$/);
  await expect(entryDetailPage.titleHeading).toHaveText(updatedTitle);
  await expect(entryDetailPage.text('playwright-updated')).toBeVisible();
});