// Poster board: open from the timeline, filter, read a poster, export a
// self-contained HTML hand-off and confirm it works without the app.

import { readFile } from 'node:fs/promises';

import { expect, test } from './helpers/harness.js';
import { EntryFormPage } from './poms/entry-form-page.js';
import { PosterBoardPage } from './poms/poster-board-page.js';
import { TimelinePage } from './poms/timeline-page.js';

// Generated by GitHub Copilot - Oct-02-2026
/** Verify rich text survives without interpreting HTML strings from board JSON. */
for (const exportMode of [false, true]) {
  test(`poster detail clones sanitized content in ${exportMode ? 'export' : 'live board'}`, async ({
    ensureDedicatedGroup,
    page,
  }) => {
    const groupId = await ensureDedicatedGroup();
    const title = `Board safe content ${Date.now()}`;
    const entryForm = new EntryFormPage(page);
    const board = new PosterBoardPage(page);
    await entryForm.gotoNew();
    await entryForm.selectTimelineGroup(groupId);
    await entryForm.fillDate('2026', '4', '3');
    await entryForm.fillTitle(title);
    await entryForm.fillEventSummary(
      '<p><strong>Bold body</strong> &amp; ' +
      '&lt;img src=x&gt;</p><ul><li><em>List item</em></li></ul>',
    );
    await entryForm.save();
    await expect(page).toHaveURL(/\/entries\/\d+\/view$/);

    const response = await page.request.get(
      `/timeline/board${exportMode ? '/export' : ''}?group_id=${groupId}`,
    );
    expect(response.ok()).toBeTruthy();
    const html = (await response.text()).replace(
      /(<script id="board-data" type="application\/json">)([\s\S]*?)(<\/script>)/,
      (_match, start: string, json: string, end: string) => {
        const payload: { items: { body_html: string }[] } = JSON.parse(json);
        for (const item of payload.items) {
          item.body_html = '<img src="invalid" data-codeql-probe="injected">';
        }
        return start + JSON.stringify(payload).replace(/</g, '\\u003c') + end;
      },
    );
    await page.route('**/*', (route) => route.abort());
    await page.setContent(html);
    await board.poster(title).click();
    await expect(board.dialog).toBeVisible();
    await expect(board.dialog.locator('.body img')).toHaveCount(0);
    await expect(board.dialog.locator('.body strong')).toHaveText('Bold body');
    await expect(board.dialog.locator('.body li em')).toHaveText('List item');
    await expect(board.dialog.locator('.body')).toContainText('& <img src=x>');
    await expect(board.closeButton).toBeFocused();
    await board.closeButton.click();
    await expect(board.dialog).toBeHidden();
    await board.poster(title).click();
    await expect(board.dialog.locator('.body strong')).toHaveText('Bold body');
  });
}

test('poster board shows scoped events and exports a self-contained HTML file', async ({
  ensureDedicatedGroup,
  page,
}) => {
  const groupId = await ensureDedicatedGroup();
  const runToken = Date.now();
  const policyTitle = `Board policy event ${runToken}`;
  const launchTitle = `Board launch event ${runToken}`;
  const entryFormPage = new EntryFormPage(page);
  const board = new PosterBoardPage(page);

  for (const [title, day, tags] of [
    [policyTitle, '3', 'policy'],
    [launchTitle, '9', 'launch'],
  ] as const) {
    await entryFormPage.gotoNew();
    await entryFormPage.selectTimelineGroup(groupId);
    await entryFormPage.fillDate('2026', '4', day);
    await entryFormPage.fillTitle(title);
    await entryFormPage.fillEventSummary(`${title} summary for the poster board.`);
    await entryFormPage.fillTags(tags);
    await entryFormPage.save();
    await expect(page).toHaveURL(/\/entries\/\d+\/view$/);
  }

  await new TimelinePage(page).goto(groupId);
  await page.getByRole('link', { name: 'Poster Board' }).click();
  await expect(page).toHaveURL(new RegExp(`/timeline/board\\?group_id=${groupId}$`));
  await expect(page).toHaveTitle(/Poster Board$/);

  await expect(board.poster(policyTitle)).toBeVisible();
  await expect(board.poster(launchTitle)).toBeVisible();
  await expect(board.pinnedCount).toHaveText('2');

  await board.chooseCategory('policy');
  await expect(board.poster(launchTitle)).toHaveCount(0);
  await expect(board.poster(policyTitle)).toBeVisible();
  await board.chooseCategory('All');

  await board.search('no such poster');
  await expect(board.emptyMessage).toBeVisible();
  await board.search('');
  await expect(board.posters).toHaveCount(2);

  await board.poster(launchTitle).click();
  await expect(board.dialog).toBeVisible();
  await expect(board.dialogHeading).toHaveText(launchTitle);
  await expect(board.dialog.getByRole('link', { name: /Open full entry/ })).toBeVisible();
  await board.nextButton.click();
  await expect(board.dialogHeading).toHaveText(policyTitle);
  await board.closeButton.click();
  await expect(board.dialog).toBeHidden();

  const downloadPromise = page.waitForEvent('download');
  await board.exportLink.click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/^EventTracker-board-.+\.html$/);
  const exportPath = await download.path();
  const exportedHtml = await readFile(exportPath, 'utf-8');

  // The exported file must render on its own: block every request while it loads.
  await page.route('**/*', (route) => route.abort());
  await page.setContent(exportedHtml);
  await expect(board.poster(policyTitle)).toBeVisible();
  await expect(board.poster(launchTitle)).toBeVisible();
  await expect(board.exportLink).toHaveCount(0);

  await board.poster(policyTitle).click();
  await expect(board.dialogHeading).toHaveText(policyTitle);
  await expect(board.dialog.getByRole('link', { name: /Open full entry/ })).toHaveCount(0);
});

/** Returns the entry id from an /entries/{id}/view URL. */
function entryIdFromUrl(url: string): number {
  const match = /\/entries\/(\d+)\/view$/.exec(new URL(url).pathname);
  if (!match) throw new Error(`Not an entry view URL: ${url}`);
  return Number(match[1]);
}

test('red string overlay ties connected posters together and springs back when plucked', async ({
  ensureDedicatedGroup,
  page,
}) => {
  const groupId = await ensureDedicatedGroup();
  const runToken = Date.now();
  const entryForm = new EntryFormPage(page);
  const board = new PosterBoardPage(page);
  const titles = ['Suspect', 'Witness', 'Alibi', 'Bystander'].map(
    (name) => `${name} ${runToken}`,
  );
  const ids: number[] = [];
  for (const [index, title] of titles.entries()) {
    await entryForm.gotoNew();
    await entryForm.selectTimelineGroup(groupId);
    await entryForm.fillDate('2026', '5', String(index + 2));
    await entryForm.fillTitle(title);
    await entryForm.fillEventSummary(`${title} summary for the red string board.`);
    await entryForm.save();
    await expect(page).toHaveURL(/\/entries\/\d+\/view$/);
    ids.push(entryIdFromUrl(page.url()));
  }
  const [suspect, witness, alibi, bystander] = ids;

  // Wire Suspect-Witness (stored in both directions) and Witness-Alibi into the
  // board payload, leaving Bystander unconnected.
  const response = await page.request.get(`/timeline/board?group_id=${groupId}`);
  expect(response.ok()).toBeTruthy();
  const links: Record<number, number[]> = {
    [suspect]: [witness],
    [witness]: [suspect, alibi],
    [alibi]: [witness],
  };
  const html = (await response.text()).replace(
    /(<script id="board-data" type="application\/json">)([\s\S]*?)(<\/script>)/,
    (_match, start: string, json: string, end: string) => {
      const payload: { items: { id: number; connections: object[] }[] } = JSON.parse(json);
      for (const item of payload.items) {
        item.connections = (links[item.id] ?? []).map((id) => ({
          id,
          title: `entry ${id}`,
          date: 'May 2026',
          note: 'linked',
        }));
      }
      return start + JSON.stringify(payload).replace(/</g, '\u003c') + end;
    },
  );
  await page.setViewportSize({ width: 1280, height: 860 });
  await page.route('**/*', (route) => route.abort());
  await page.setContent(html);

  await expect(board.stringToggle).toBeVisible();
  await expect(board.stringToggle).toHaveAttribute('aria-pressed', 'false');
  await expect(board.stringToggle).toContainText('2');
  await expect(board.strings).toHaveCount(0);

  await board.stringToggle.click();
  await expect(board.stringToggle).toHaveAttribute('aria-pressed', 'true');
  await expect(board.strings).toHaveCount(2);
  await expect(board.string(suspect, witness)).toHaveCount(1);
  await expect(board.string(witness, alibi)).toHaveCount(1);
  // Every connected poster is tacked; strings leaving through the same edge share a tack.
  for (const id of [suspect, witness, alibi]) {
    await expect(board.tacks.and(page.locator(`[data-id="${id}"]`)).first()).toBeAttached();
  }
  await expect(page.locator(`svg.strings .tack[data-id="${bystander}"]`)).toHaveCount(0);
  await expect(page.locator(`.poster[data-key="${bystander}"]`)).not.toHaveClass(/\blinked\b/);
  await expect(page.locator(`.poster[data-key="${witness}"]`)).toHaveClass(/\blinked\b/);

  // Pluck the Suspect-Witness string: it follows the pointer, then springs home.
  const core = board.string(suspect, witness).locator('.yarn__core');
  // Strings are drawn in slack and pull taut; wait for the rest shape to settle.
  await expect.poll(async () => {
    const before = await core.getAttribute('d');
    await page.waitForTimeout(250);
    return before === (await core.getAttribute('d'));
  }, { timeout: 5000 }).toBe(true);
  const restPath = await core.getAttribute('d');
  // The yarn runs behind the posters: grab it where it crosses open cork.
  const grip = await board.string(suspect, witness).locator('.yarn__hit').evaluate((path) => {
    const hit = path as SVGPathElement;
    const box = (hit.ownerSVGElement as SVGSVGElement).getBoundingClientRect();
    const length = hit.getTotalLength();
    for (let step = 1; step < 40; step++) {
      const t = 0.5 + (step % 2 ? 1 : -1) * Math.floor(step / 2) * 0.025;
      const point = hit.getPointAtLength(length * t);
      const x = box.left + point.x;
      const y = box.top + point.y;
      if (document.elementFromPoint(x, y) === hit) return { x, y };
    }
    throw new Error('No exposed stretch of yarn to grab');
  });
  await page.mouse.move(grip.x, grip.y);
  await page.mouse.down();
  await page.mouse.move(grip.x + 30, grip.y + 90, { steps: 4 });
  await expect(core).not.toHaveAttribute('d', restPath ?? '');
  await page.mouse.up();
  await expect.poll(() => core.getAttribute('d'), { timeout: 4000 }).toBe(restPath);
  // A pluck is not a click: the connection card stays shut.
  await expect(board.connectionCard).toBeHidden();

  // Clicking a string explains the connection.
  await page.mouse.click(grip.x, grip.y);
  await expect(board.connectionCard).toBeVisible();
  await expect(board.connectionCard).toContainText(titles[0]);
  await expect(board.connectionCard).toContainText(titles[1]);
  await expect(board.connectionCard).toContainText('linked');
  await expect(board.connectionCard).toContainText('1 day apart');
  await page.keyboard.press('Escape');
  await expect(board.connectionCard).toBeHidden();

  // Right-click works too, and an end of the string opens that poster.
  await page.mouse.click(grip.x, grip.y, { button: 'right' });
  await expect(board.connectionCard).toBeVisible();
  await board.connectionCard.getByRole('button', { name: new RegExp(titles[1]) }).click();
  await expect(board.connectionCard).toBeHidden();
  await expect(board.dialogHeading).toHaveText(titles[1]);
  await board.closeButton.click();
  await expect(board.dialog).toBeHidden();

  // Filtering out the hub poster leaves nothing to tie together.
  await board.search(titles[3]);
  await expect(board.strings).toHaveCount(0);
  await expect(board.stringToggle).toBeDisabled();
  await board.search('');
  await expect(board.strings).toHaveCount(2);

  await board.stringToggle.click();
  await expect(board.stringToggle).toHaveAttribute('aria-pressed', 'false');
  await expect(board.strings).toHaveCount(0);
});

test('red string waits for posters to land, keeps decorations clear, and spotlights on hover', async ({
  ensureDedicatedGroup,
  page,
}) => {
  const groupId = await ensureDedicatedGroup();
  const runToken = Date.now();
  const entryForm = new EntryFormPage(page);
  const board = new PosterBoardPage(page);
  const titles = ['Hub', 'Spoke', 'Rim', 'Loner'].map((name) => `${name} ${runToken}`);
  const ids: number[] = [];
  for (const [index, title] of titles.entries()) {
    await entryForm.gotoNew();
    await entryForm.selectTimelineGroup(groupId);
    await entryForm.fillDate('2026', '6', String(index + 2));
    await entryForm.fillTitle(title);
    await entryForm.fillEventSummary(`${title} summary for the spotlight board.`);
    await entryForm.save();
    await expect(page).toHaveURL(/\/entries\/\d+\/view$/);
    ids.push(entryIdFromUrl(page.url()));
  }
  const [hub, spoke, rim, loner] = ids;
  const links: Record<number, number[]> = { [hub]: [spoke, rim], [spoke]: [hub], [rim]: [hub] };

  const boardPath = `/timeline/board?group_id=${groupId}`;
  const response = await page.request.get(boardPath);
  expect(response.ok()).toBeTruthy();
  const html = (await response.text()).replace(
    /(<script id="board-data" type="application\/json">)([\s\S]*?)(<\/script>)/,
    (_match, start: string, json: string, end: string) => {
      const payload: { items: { id: number; connections: object[] }[] } = JSON.parse(json);
      for (const item of payload.items) {
        item.connections = (links[item.id] ?? []).map((id) => ({
          id, title: `entry ${id}`, date: 'Jun 2026', note: 'linked',
        }));
      }
      return start + JSON.stringify(payload).replace(/</g, '\u003c') + end;
    },
  );
  // Strings already switched on, and a probe that timestamps the first frame
  // with every poster at full size versus the first frame with visible yarn.
  await page.addInitScript(() => {
    localStorage.setItem('eventtracker.posterBoard.strings', '1');
    const probe: { landed?: number; strung?: number } = {};
    (window as unknown as { __probe: typeof probe }).__probe = probe;
    const tick = () => {
      const now = performance.now();
      const papers = [...document.querySelectorAll('.poster .paper')];
      if (probe.landed === undefined && papers.length && papers.every((paper) => {
        const m = new DOMMatrix(getComputedStyle(paper).transform);
        return Math.hypot(m.a, m.b) > 0.999;
      })) probe.landed = now;
      const yarn = document.querySelector('svg.strings--yarn');
      const core = yarn?.querySelector('.yarn__core');
      if (probe.strung === undefined && yarn && core &&
          getComputedStyle(yarn).visibility === 'visible' &&
          parseFloat(getComputedStyle(core).strokeDashoffset || '0') < 0.99) probe.strung = now;
      if (now < 6000) requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  });
  await page.route(`**${boardPath}`, (route) => route.fulfill({ body: html, contentType: 'text/html' }));
  await page.setViewportSize({ width: 1280, height: 860 });
  await page.goto(boardPath);

  await expect(board.stringToggle).toHaveAttribute('aria-pressed', 'true');
  await expect(board.strings).toHaveCount(2);
  type Probe = { landed?: number; strung?: number };
  const readProbe = () => page.evaluate(() => (window as unknown as { __probe: Probe }).__probe);
  await expect.poll(async () => {
    const p = await readProbe();
    return p.landed !== undefined && p.strung !== undefined;
  }, { timeout: 6000 }).toBe(true);
  const probe = (await readProbe()) as Required<Probe>;
  expect(probe.strung).toBeGreaterThanOrEqual(probe.landed);

  // Decorations only ever sit on open cork.
  const overlaps = await page.evaluate(() => {
    const papers = [...document.querySelectorAll('.poster.in .paper')].map((el) => el.getBoundingClientRect());
    const stickers = [...document.querySelectorAll('.sticker > *')].map((el) => el.getBoundingClientRect());
    let hits = 0;
    for (const s of stickers) for (const c of papers) {
      if (s.left < c.right && s.right > c.left && s.top < c.bottom && s.bottom > c.top) hits++;
    }
    return { hits, stickers: stickers.length };
  });
  expect(overlaps.hits).toBe(0);

  const paper = (id: number) => page.locator(`.poster[data-key="${id}"] .paper`);
  const opacity = (id: number) => paper(id).evaluate((el) => Number(getComputedStyle(el).opacity));

  // Hovering the hub lights its strings and fades the poster it has no tie to.
  await paper(hub).hover();
  await expect(board.string(hub, spoke)).toHaveClass(/\bhot\b/);
  await expect(board.string(hub, rim)).toHaveClass(/\bhot\b/);
  await expect.poll(() => opacity(loner)).toBeLessThan(0.5);
  expect(await opacity(spoke)).toBe(1);
  expect(await opacity(hub)).toBe(1);

  // Hovering a spoke: the rim is unrelated to it, so it fades too.
  await paper(spoke).hover();
  await expect(board.string(hub, rim)).not.toHaveClass(/\bhot\b/);
  await expect.poll(() => opacity(rim)).toBeLessThan(0.5);

  await page.mouse.move(2, 2);
  await expect.poll(() => opacity(rim)).toBe(1);
  await expect(page.locator('body')).not.toHaveClass(/\bboard-focus\b/);

  // Keyboard focus spotlights exactly like hover.
  await paper(rim).focus();
  await expect(board.string(hub, rim)).toHaveClass(/\bhot\b/);
  await expect.poll(() => opacity(spoke)).toBeLessThan(0.5);
});
