// Poster board: open from the timeline, filter, read a poster, export a
// self-contained HTML hand-off and confirm it works without the app.

import { readFile } from 'node:fs/promises';

import { expect, test } from './helpers/harness.js';
import { EntryFormPage } from './poms/entry-form-page.js';
import { PosterBoardPage } from './poms/poster-board-page.js';
import { TimelinePage } from './poms/timeline-page.js';

// Generated by GitHub Copilot - Oct-02-2026
/** Verify rich text survives without interpreting HTML strings from board JSON. */
for (const exportMode of [false, true]) {
  test(`poster detail clones sanitized content in ${exportMode ? 'export' : 'live board'}`, async ({
    ensureDedicatedGroup,
    page,
  }) => {
    const groupId = await ensureDedicatedGroup();
    const title = `Board safe content ${Date.now()}`;
    const entryForm = new EntryFormPage(page);
    const board = new PosterBoardPage(page);
    await entryForm.gotoNew();
    await entryForm.selectTimelineGroup(groupId);
    await entryForm.fillDate('2026', '4', '3');
    await entryForm.fillTitle(title);
    await entryForm.fillEventSummary(
      '<p><strong>Bold body</strong> &amp; ' +
      '&lt;img src=x&gt;</p><ul><li><em>List item</em></li></ul>',
    );
    await entryForm.save();
    await expect(page).toHaveURL(/\/entries\/\d+\/view$/);

    const response = await page.request.get(
      `/timeline/board${exportMode ? '/export' : ''}?group_id=${groupId}`,
    );
    expect(response.ok()).toBeTruthy();
    const html = (await response.text()).replace(
      /(<script id="board-data" type="application\/json">)([\s\S]*?)(<\/script>)/,
      (_match, start: string, json: string, end: string) => {
        const payload: { items: { body_html: string }[] } = JSON.parse(json);
        for (const item of payload.items) {
          item.body_html = '<img src="invalid" data-codeql-probe="injected">';
        }
        return start + JSON.stringify(payload).replace(/</g, '\\u003c') + end;
      },
    );
    await page.route('**/*', (route) => route.abort());
    await page.setContent(html);
    await board.poster(title).click();
    await expect(board.dialog).toBeVisible();
    await expect(board.dialog.locator('.body img')).toHaveCount(0);
    await expect(board.dialog.locator('.body strong')).toHaveText('Bold body');
    await expect(board.dialog.locator('.body li em')).toHaveText('List item');
    await expect(board.dialog.locator('.body')).toContainText('& <img src=x>');
    await expect(board.closeButton).toBeFocused();
    await board.closeButton.click();
    await expect(board.dialog).toBeHidden();
    await board.poster(title).click();
    await expect(board.dialog.locator('.body strong')).toHaveText('Bold body');
  });
}

test('poster board shows scoped events and exports a self-contained HTML file', async ({
  ensureDedicatedGroup,
  page,
}) => {
  const groupId = await ensureDedicatedGroup();
  const runToken = Date.now();
  const policyTitle = `Board policy event ${runToken}`;
  const launchTitle = `Board launch event ${runToken}`;
  const entryFormPage = new EntryFormPage(page);
  const board = new PosterBoardPage(page);

  for (const [title, day, tags] of [
    [policyTitle, '3', 'policy'],
    [launchTitle, '9', 'launch'],
  ] as const) {
    await entryFormPage.gotoNew();
    await entryFormPage.selectTimelineGroup(groupId);
    await entryFormPage.fillDate('2026', '4', day);
    await entryFormPage.fillTitle(title);
    await entryFormPage.fillEventSummary(`${title} summary for the poster board.`);
    await entryFormPage.fillTags(tags);
    await entryFormPage.save();
    await expect(page).toHaveURL(/\/entries\/\d+\/view$/);
  }

  await new TimelinePage(page).goto(groupId);
  await page.getByRole('link', { name: 'Poster Board' }).click();
  await expect(page).toHaveURL(new RegExp(`/timeline/board\\?group_id=${groupId}$`));
  await expect(page).toHaveTitle(/Poster Board$/);

  await expect(board.poster(policyTitle)).toBeVisible();
  await expect(board.poster(launchTitle)).toBeVisible();
  await expect(board.pinnedCount).toHaveText('2');

  await board.chooseCategory('policy');
  await expect(board.poster(launchTitle)).toHaveCount(0);
  await expect(board.poster(policyTitle)).toBeVisible();
  await board.chooseCategory('All');

  await board.search('no such poster');
  await expect(board.emptyMessage).toBeVisible();
  await board.search('');
  await expect(board.posters).toHaveCount(2);

  await board.poster(launchTitle).click();
  await expect(board.dialog).toBeVisible();
  await expect(board.dialogHeading).toHaveText(launchTitle);
  await expect(board.dialog.getByRole('link', { name: /Open full entry/ })).toBeVisible();
  await board.nextButton.click();
  await expect(board.dialogHeading).toHaveText(policyTitle);
  await board.closeButton.click();
  await expect(board.dialog).toBeHidden();

  const downloadPromise = page.waitForEvent('download');
  await board.exportLink.click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/^EventTracker-board-.+\.html$/);
  const exportPath = await download.path();
  const exportedHtml = await readFile(exportPath, 'utf-8');

  // The exported file must render on its own: block every request while it loads.
  await page.route('**/*', (route) => route.abort());
  await page.setContent(exportedHtml);
  await expect(board.poster(policyTitle)).toBeVisible();
  await expect(board.poster(launchTitle)).toBeVisible();
  await expect(board.exportLink).toHaveCount(0);

  await board.poster(policyTitle).click();
  await expect(board.dialogHeading).toHaveText(policyTitle);
  await expect(board.dialog.getByRole('link', { name: /Open full entry/ })).toHaveCount(0);
});
