// Generated by GitHub Copilot
import { expect, test } from './helpers/harness.js';

test('loads the main timeline and shows the app title', async ({ page }) => {
  await page.goto('/');

  await expect(page).toHaveURL(/\/$/);
  await expect(page).toHaveTitle(/Timeline \| Events$/);
});