// Generated by GitHub Copilot
// Scenario 1: Timeline navigation and view switching
// 1. Open /
// 2. Assert the page title, main heading, and current group label are visible.
// 3. Assert the timeline view controls are present and Details is active by default.
// 4. Switch to Months and assert the current-view label changes to Months.
// 5. Assert at least one month bucket card is rendered with an Open ... drill-in button and a Start story link.
// 6. Switch to Summaries and assert the visible view state changes again.

import { expect, test } from './helpers/harness.js';
import { EntryFormPage } from './poms/entry-form-page.js';
import { TimelinePage } from './poms/timeline-page.js';

test('scenario 1: timeline navigation and view switching', async ({ ensureDedicatedGroup, page }) => {
  const groupId = await ensureDedicatedGroup();
  const uniqueTitle = `Timeline Scenario Entry ${Date.now()}`;
  const entryFormPage = new EntryFormPage(page);
  const timelinePage = new TimelinePage(page);

  await entryFormPage.gotoNew();
  await entryFormPage.selectTimelineGroup(groupId);
  await entryFormPage.fillDate('2026', '4', '2');
  await entryFormPage.fillTitle(uniqueTitle);
  await entryFormPage.fillEventSummary('Timeline scenario seed entry.');
  await entryFormPage.save();

  await expect(page).toHaveURL(/\/entries\/\d+\/view$/);

  await timelinePage.goto(groupId);

  await expect(page).toHaveURL(new RegExp(`/\\?group_id=${groupId}$`));
  await expect(page).toHaveTitle(/Timeline \| Events$/);
  await expect(timelinePage.eventsLink).toBeVisible();
  await expect(timelinePage.exportLink).toBeVisible();
  await expect(timelinePage.adminLink).toBeVisible();
  await expect(timelinePage.newEntryLink).toBeVisible();

  await expect(timelinePage.heading).toContainText('Timeline');
  await expect(timelinePage.groupValue).toBeVisible();

  await expect(timelinePage.viewControls).toBeVisible();
  await expect(timelinePage.detailsButton).toHaveAttribute('aria-pressed', 'true');
  await expect(timelinePage.currentViewLabel).toHaveText('Details');

  await timelinePage.showMonths();
  await expect(timelinePage.monthsButton).toHaveAttribute('aria-pressed', 'true');
  await expect(timelinePage.currentViewLabel).toHaveText('Months');

  await expect(timelinePage.firstMonthBucket()).toBeVisible();
  await expect(timelinePage.firstOpenButton()).toBeVisible();
  await expect(timelinePage.firstStartStoryLink()).toBeVisible();

  await timelinePage.showSummaries();
  await expect(timelinePage.summariesButton).toHaveAttribute('aria-pressed', 'true');
  await expect(timelinePage.currentViewLabel).toHaveText('Summaries');
});