// Generated by GitHub Copilot
import fs from 'node:fs/promises';
import process from 'node:process';
import { createRequire } from 'node:module';

import { Marpit } from '@marp-team/marpit';

const require = createRequire(import.meta.url);
const { version: marpitVersion } = require('@marp-team/marpit/package.json');

const EXECUTIVE_THEME_CSS = String.raw`/* @theme eventtracker-executive */
section {
  width: 1280px;
  height: 720px;
  padding: 56px 72px 60px;
  background:
    radial-gradient(ellipse 80% 60% at 95% 5%, rgba(14, 165, 233, 0.12), transparent),
    radial-gradient(ellipse 50% 50% at 5% 95%, rgba(99, 102, 241, 0.06), transparent),
    linear-gradient(175deg, #f8fafc 0%, #eef2ff 52%, #f0f9ff 100%);
  color: #0f172a;
  font-family: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif;
  font-size: 26px;
  line-height: 1.5;
}

section::after {
  content: attr(data-marpit-pagination) ' / ' attr(data-marpit-pagination-total);
  position: absolute;
  right: 72px;
  bottom: 28px;
  color: #94a3b8;
  font-size: 13px;
  font-weight: 500;
  letter-spacing: 0.1em;
  font-variant-numeric: tabular-nums;
}

h1 {
  margin: 0 0 12px;
  font-size: 52px;
  font-weight: 700;
  line-height: 1.1;
  letter-spacing: -0.035em;
  color: #0f172a;
}

h2 {
  margin: 0 0 8px;
  font-size: 32px;
  font-weight: 600;
  letter-spacing: -0.02em;
  color: #1e293b;
}

h3,
p,
ul,
ol,
blockquote {
  margin: 0;
}

/* ---- slide grid ---- */
.et-slide {
  display: grid;
  gap: 20px;
  height: 100%;
  grid-template-rows: auto 1fr auto;
}

.et-slide-header {
  display: grid;
  gap: 8px;
}

.et-slide-kicker {
  color: #0284c7;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.18em;
  text-transform: uppercase;
}

.et-slide-subtitle {
  max-width: 860px;
  color: #475569;
  font-size: 22px;
  line-height: 1.45;
}

/* ---- body points ---- */
.et-point-list ul {
  display: grid;
  gap: 10px;
  padding-left: 22px;
}

.et-point-list li {
  padding-left: 4px;
  line-height: 1.45;
}

.et-point-list li::marker {
  color: #0ea5e9;
}

/* ---- callouts ---- */
.et-callout-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 14px;
}

.et-callout {
  padding: 18px 20px;
  border: 1px solid rgba(14, 165, 233, 0.14);
  border-radius: 14px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.92) 0%, rgba(240, 249, 255, 0.6) 100%);
  box-shadow: 0 1px 3px rgba(15, 23, 42, 0.06), 0 8px 24px rgba(15, 23, 42, 0.04);
  font-size: 20px;
  line-height: 1.4;
}

/* ---- KPI strip ---- */
.et-kpi-strip {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
  gap: 14px;
}

.et-kpi-card {
  display: grid;
  gap: 10px;
  min-height: 120px;
  padding: 20px 22px;
  border-radius: 16px;
  background: linear-gradient(145deg, #0f172a 0%, #1e293b 60%, #0c4a6e 100%);
  color: #e2e8f0;
  box-shadow: 0 4px 16px rgba(15, 23, 42, 0.18);
}

.et-kpi-card strong {
  font-size: 24px;
  line-height: 1.25;
  color: #f1f5f9;
}

.et-kpi-label {
  color: #7dd3fc;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

/* ---- phase timeline ---- */
.et-phase-timeline {
  display: grid;
  gap: 10px;
  padding: 20px 24px 20px 44px;
  border-radius: 14px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.95) 0%, rgba(241, 245, 249, 0.8) 100%);
  box-shadow: 0 1px 3px rgba(15, 23, 42, 0.06), 0 8px 24px rgba(15, 23, 42, 0.04);
  counter-reset: phase;
}

.et-phase-timeline li {
  padding-left: 8px;
  line-height: 1.4;
}

.et-phase-timeline li::marker {
  color: #0284c7;
  font-weight: 700;
}

/* ---- pull quote ---- */
.et-pull-quote {
  padding: 28px 32px;
  border-left: 5px solid #0ea5e9;
  border-radius: 0 14px 14px 0;
  background: linear-gradient(135deg, rgba(14, 165, 233, 0.06) 0%, rgba(99, 102, 241, 0.04) 100%);
}

.et-pull-quote p {
  font-size: 30px;
  font-weight: 600;
  line-height: 1.3;
  color: #1e293b;
  font-style: italic;
}

/* ---- sources footer ---- */
.et-slide-sources {
  margin-top: auto;
  padding-top: 12px;
  border-top: 1px solid rgba(15, 23, 42, 0.08);
  color: #94a3b8;
  font-size: 13px;
  line-height: 1.6;
}

.et-source-link {
  color: #0369a1;
  text-decoration: none;
  margin-right: 10px;
  font-weight: 500;
}

.et-source-link:hover {
  text-decoration: underline;
}

/* ---- title slide ---- */
.et-slide--title {
  justify-content: center;
  text-align: center;
  background:
    radial-gradient(ellipse 70% 50% at 50% 40%, rgba(14, 165, 233, 0.1), transparent),
    radial-gradient(ellipse 40% 40% at 80% 80%, rgba(99, 102, 241, 0.06), transparent),
    linear-gradient(175deg, #f8fafc 0%, #eef2ff 52%, #f0f9ff 100%);
}

.et-slide--title .et-slide-header {
  align-items: center;
  gap: 14px;
}

.et-slide--title h1 {
  max-width: 960px;
  font-size: 62px;
  margin-bottom: 18px;
  padding-bottom: 6px;
  line-height: 1.16;
  letter-spacing: -0.04em;
  background: linear-gradient(135deg, #0f172a 0%, #0c4a6e 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.et-slide--title .et-slide-subtitle {
  font-size: 24px;
  line-height: 1.55;
  color: #64748b;
  max-width: 700px;
}

/* ---- summary slide ---- */
.et-slide--summary {
  background:
    radial-gradient(ellipse 60% 50% at 90% 10%, rgba(14, 165, 233, 0.1), transparent),
    linear-gradient(175deg, #f8fafc 0%, #eef2ff 60%, #f0f9ff 100%);
}

/* ---- turning point slide ---- */
.et-slide--turning_point .et-slide-kicker {
  color: #d97706;
}

/* ---- toc slide ---- */
.et-slide--toc {
  background:
    radial-gradient(ellipse 50% 40% at 85% 15%, rgba(14, 165, 233, 0.08), transparent),
    linear-gradient(175deg, #f8fafc 0%, #f0f9ff 52%, #eef2ff 100%);
}

.et-slide--toc .et-point-list ul {
  display: grid;
  gap: 14px;
  padding-left: 28px;
  font-size: 28px;
  font-weight: 500;
}

.et-slide--toc .et-point-list li::marker {
  color: #0284c7;
  font-weight: 700;
}

/* ---- section header slide ---- */
.et-slide--section_header {
  justify-content: center;
  text-align: left;
  background:
    radial-gradient(ellipse 80% 60% at 80% 30%, rgba(14, 165, 233, 0.14), transparent),
    radial-gradient(ellipse 50% 50% at 10% 80%, rgba(99, 102, 241, 0.08), transparent),
    linear-gradient(175deg, #0f172a 0%, #1e293b 60%, #0c4a6e 100%);
  color: #e2e8f0;
}

.et-slide--section_header .et-slide-kicker {
  color: #38bdf8;
}

.et-slide--section_header h1 {
  font-size: 56px;
  color: #f1f5f9;
  max-width: 900px;
}

.et-slide--section_header .et-slide-subtitle,
.et-slide--section_header .et-callout {
  color: #94a3b8;
  font-size: 24px;
  background: none;
  border: none;
  box-shadow: none;
  padding: 0;
}

.et-slide--section_header .et-slide-sources {
  border-top-color: rgba(255, 255, 255, 0.1);
  color: #64748b;
}

.et-slide--section_header .et-source-link {
  color: #38bdf8;
}

/* ---- highlight slide ---- */
.et-slide--highlight {
  background:
    radial-gradient(ellipse 60% 50% at 10% 90%, rgba(14, 165, 233, 0.1), transparent),
    linear-gradient(175deg, #f8fafc 0%, #f0f9ff 60%, #eef2ff 100%);
}

.et-slide--highlight .et-slide-kicker {
  color: #059669;
}

/* ---- close slide ---- */
.et-slide--close {
  background:
    radial-gradient(ellipse 70% 50% at 50% 60%, rgba(56, 189, 248, 0.12), transparent),
    radial-gradient(ellipse 40% 40% at 20% 20%, rgba(99, 102, 241, 0.06), transparent),
    linear-gradient(175deg, #f8fafc 0%, #e0f2fe 60%, #eef2ff 100%);
}

.et-slide--close h1 {
  font-size: 44px;
}

/* ---- thank you slide ---- */
.et-slide--thank_you {
  justify-content: center;
  text-align: center;
  background:
    radial-gradient(ellipse 70% 50% at 50% 40%, rgba(14, 165, 233, 0.12), transparent),
    radial-gradient(ellipse 50% 50% at 80% 80%, rgba(99, 102, 241, 0.08), transparent),
    linear-gradient(175deg, #0f172a 0%, #1e293b 60%, #0c4a6e 100%);
  color: #e2e8f0;
}

.et-slide--thank_you .et-slide-header {
  align-items: center;
}

.et-slide--thank_you .et-slide-kicker {
  color: #38bdf8;
}

.et-slide--thank_you h1 {
  font-size: 72px;
  background: linear-gradient(135deg, #38bdf8 0%, #818cf8 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.et-slide--thank_you .et-slide-subtitle {
  color: #94a3b8;
  font-size: 24px;
}

.et-slide--thank_you .et-point-list,
.et-slide--thank_you .et-point-list li,
.et-slide--thank_you .et-callout,
.et-slide--thank_you .et-pull-quote p,
.et-slide--thank_you .et-phase-timeline li,
.et-slide--thank_you .et-bar-label,
.et-slide--thank_you .et-icon-label {
  color: #e2e8f0;
}

.et-slide--thank_you .et-point-list li::marker,
.et-slide--thank_you .et-phase-timeline li::marker {
  color: #7dd3fc;
}

.et-slide--thank_you .et-callout,
.et-slide--thank_you .et-pull-quote,
.et-slide--thank_you .et-phase-timeline,
.et-slide--thank_you .et-bar-chart,
.et-slide--thank_you .et-icon-item {
  background: rgba(15, 23, 42, 0.28);
  border-color: rgba(125, 211, 252, 0.35);
  box-shadow: none;
}

.et-slide--thank_you .et-slide-sources {
  border-top-color: rgba(255, 255, 255, 0.1);
  color: #64748b;
}

.et-slide--thank_you .et-source-link {
  color: #7dd3fc;
}

/* ---- bar chart visual ---- */
.et-bar-chart {
  display: grid;
  gap: 12px;
  padding: 20px 24px;
  border-radius: 14px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.95) 0%, rgba(241, 245, 249, 0.8) 100%);
  box-shadow: 0 1px 3px rgba(15, 23, 42, 0.06), 0 8px 24px rgba(15, 23, 42, 0.04);
}

.et-bar-row {
  display: grid;
  grid-template-columns: 160px 1fr;
  gap: 14px;
  align-items: center;
}

.et-bar-label {
  font-size: 15px;
  font-weight: 600;
  color: #334155;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.et-bar-track {
  height: 28px;
  background: #e2e8f0;
  border-radius: 6px;
  overflow: hidden;
}

.et-bar-fill {
  height: 100%;
  border-radius: 6px;
  background: linear-gradient(90deg, #0ea5e9 0%, #38bdf8 100%);
}

/* ---- stat card visual ---- */
.et-stat-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 14px;
}

.et-stat-card {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100px;
  padding: 20px 22px;
  border-radius: 16px;
  background: linear-gradient(145deg, #0f172a 0%, #1e293b 60%, #0c4a6e 100%);
  box-shadow: 0 4px 16px rgba(15, 23, 42, 0.18);
  text-align: center;
}

.et-stat-value {
  font-size: 28px;
  font-weight: 700;
  line-height: 1.2;
  color: #38bdf8;
}

/* ---- icon grid visual ---- */
.et-icon-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 12px;
}

.et-icon-item {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 14px 16px;
  border-radius: 12px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.95) 0%, rgba(240, 249, 255, 0.6) 100%);
  border: 1px solid rgba(14, 165, 233, 0.12);
  box-shadow: 0 1px 3px rgba(15, 23, 42, 0.04);
}

.et-icon-symbol {
  flex-shrink: 0;
  color: #0284c7;
  font-size: 16px;
  line-height: 1.5;
}

.et-icon-label {
  font-size: 18px;
  font-weight: 500;
  line-height: 1.4;
  color: #1e293b;
}
`;

/**
 * Read markdown from stdin or from a file path passed as the first argument.
 * @returns {Promise<string>}
 */
async function readMarkdown() {
  const filePath = process.argv[2];
  if (filePath && filePath !== '-') {
    return fs.readFile(filePath, 'utf8');
  }

  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  const markdown = Buffer.concat(chunks).toString('utf8').trim();
  if (!markdown) {
    throw new Error('No deck markdown was provided to the Marpit renderer.');
  }
  return markdown;
}

/**
 * Render the provided markdown into Marpit HTML and CSS.
 * @param {string} markdown
 * @returns {{ html: string, css: string }}
 */
function renderDeck(markdown) {
  const marpit = new Marpit({ markdown: { html: true } });
  marpit.themeSet.default = marpit.themeSet.add(EXECUTIVE_THEME_CSS);
  const { html, css } = marpit.render(markdown);
  return {
    html: String(html),
    css: String(css),
  };
}

try {
  const markdown = await readMarkdown();
  const renderedDeck = renderDeck(markdown);
  process.stdout.write(
    JSON.stringify({
      ok: true,
      html: renderedDeck.html,
      css: renderedDeck.css,
      compilerName: 'marpit',
      compilerVersion: marpitVersion,
    })
  );
} catch (error) {
  process.stdout.write(
    JSON.stringify({
      ok: false,
      error:
        error instanceof Error
          ? error.message
          : 'Executive presentation generation failed.',
    })
  );
  process.exitCode = 1;
}